version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/client/go"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "Asia/Tokyo"
