services:
  oapi-codegen:
    build:
      context: .
      dockerfile: Dockerfile.oapi-codegen
    container_name: oapi-codegen
    working_dir: /tmp
    volumes:
      - ./docs/swagger.yml:/tmp/swagger.yml
      - ./oapiconfig.yaml:/tmp/oapiconfig.yaml
      - ./client/go_v2:/tmp/go_v2
    command: |-
      oapi-codegen -config /tmp/oapiconfig.yaml /tmp/swagger.yml