services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./docs/swagger.yml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml