/*
KING OF TIME WebAPI

Testing RequestApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sam8helloworld/kot-api-docs"
)

func Test_openapi_RequestApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RequestApiService GetSchedules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var date string

		resp, httpRes, err := apiClient.RequestApi.GetSchedules(context.Background(), date).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
