/*
KING OF TIME WebAPI

Testing AdministratorApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"testing"

	openapiclient "github.com/sam8helloworld/kot-api-docs"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_AdministratorApiService(t *testing.T) {
	configuration := configuration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AdministratorApiService GetAdministrators", func(t *testing.T) {
		ctx := contextWithAuthorization()
		resp, httpRes, err := apiClient.AdministratorApi.GetAdministrators(ctx).AdditionalFields([]string{"associatedEmployees"}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
