/*
KING OF TIME WebAPI

Testing EmployeeApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/sam8helloworld/kot-api-docs"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_EmployeeApiService(t *testing.T) {

	configuration := &openapiclient.Configuration{
		DefaultHeader: make(map[string]string),
		UserAgent:     "OpenAPI-Generator/1.0.0/go",
		Debug:         false,
		Servers: openapiclient.ServerConfigurations{
			{
				URL:         "http://localhost:8001",
				Description: "Mock server (uses example data)",
			},
		},
		OperationServers: map[string]openapiclient.ServerConfigurations{},
	}
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmployeeApiService GetEmployees", func(t *testing.T) {

		bearer := "8j9f7v4893y58rvt7nyfq2893n75tr78937n83"
		ctx := context.WithValue(context.Background(), openapiclient.ContextAccessToken, bearer)
		resp, httpRes, err := apiClient.EmployeeApi.GetEmployees(ctx).Date("2016-10-10").Division("1000").IncludeResigner(true).AdditionalFields([]string{"emailAddresses"}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
