/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DailyWorkingResponseHolidaysObtainedFulltimeHoliday type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyWorkingResponseHolidaysObtainedFulltimeHoliday{}

// DailyWorkingResponseHolidaysObtainedFulltimeHoliday struct for DailyWorkingResponseHolidaysObtainedFulltimeHoliday
type DailyWorkingResponseHolidaysObtainedFulltimeHoliday struct {
	// 休暇区分コード
	Code int32 `json:"code"`
	// 休暇区分名
	Name string `json:"name"`
}

// NewDailyWorkingResponseHolidaysObtainedFulltimeHoliday instantiates a new DailyWorkingResponseHolidaysObtainedFulltimeHoliday object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyWorkingResponseHolidaysObtainedFulltimeHoliday(code int32, name string) *DailyWorkingResponseHolidaysObtainedFulltimeHoliday {
	this := DailyWorkingResponseHolidaysObtainedFulltimeHoliday{}
	this.Code = code
	this.Name = name
	return &this
}

// NewDailyWorkingResponseHolidaysObtainedFulltimeHolidayWithDefaults instantiates a new DailyWorkingResponseHolidaysObtainedFulltimeHoliday object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyWorkingResponseHolidaysObtainedFulltimeHolidayWithDefaults() *DailyWorkingResponseHolidaysObtainedFulltimeHoliday {
	this := DailyWorkingResponseHolidaysObtainedFulltimeHoliday{}
	return &this
}

// GetCode returns the Code field value
func (o *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) SetCode(v int32) {
	o.Code = v
}

// GetName returns the Name field value
func (o *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) SetName(v string) {
	o.Name = v
}

func (o DailyWorkingResponseHolidaysObtainedFulltimeHoliday) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyWorkingResponseHolidaysObtainedFulltimeHoliday) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday struct {
	value *DailyWorkingResponseHolidaysObtainedFulltimeHoliday
	isSet bool
}

func (v NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday) Get() *DailyWorkingResponseHolidaysObtainedFulltimeHoliday {
	return v.value
}

func (v *NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday) Set(val *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday(val *DailyWorkingResponseHolidaysObtainedFulltimeHoliday) *NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday {
	return &NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday{value: val, isSet: true}
}

func (v NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyWorkingResponseHolidaysObtainedFulltimeHoliday) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


