/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DailyWorkingTimerecordResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyWorkingTimerecordResponse{}

// DailyWorkingTimerecordResponse struct for DailyWorkingTimerecordResponse
type DailyWorkingTimerecordResponse struct {
	// 日時
	Date string `json:"date"`
	// 従業員識別キー（従業員コードが変更されても不変）
	EmployeeKey string `json:"employeeKey"`
	// 打刻
	TimeRecord []DailyWorkingTimerecordResponseTimeRecordInner `json:"timeRecord"`
	CurrentDateEmployee *DailyWorkingResponseCurrentDateEmployee `json:"currentDateEmployee,omitempty"`
}

// NewDailyWorkingTimerecordResponse instantiates a new DailyWorkingTimerecordResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyWorkingTimerecordResponse(date string, employeeKey string, timeRecord []DailyWorkingTimerecordResponseTimeRecordInner) *DailyWorkingTimerecordResponse {
	this := DailyWorkingTimerecordResponse{}
	this.Date = date
	this.EmployeeKey = employeeKey
	this.TimeRecord = timeRecord
	return &this
}

// NewDailyWorkingTimerecordResponseWithDefaults instantiates a new DailyWorkingTimerecordResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyWorkingTimerecordResponseWithDefaults() *DailyWorkingTimerecordResponse {
	this := DailyWorkingTimerecordResponse{}
	return &this
}

// GetDate returns the Date field value
func (o *DailyWorkingTimerecordResponse) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingTimerecordResponse) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *DailyWorkingTimerecordResponse) SetDate(v string) {
	o.Date = v
}

// GetEmployeeKey returns the EmployeeKey field value
func (o *DailyWorkingTimerecordResponse) GetEmployeeKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmployeeKey
}

// GetEmployeeKeyOk returns a tuple with the EmployeeKey field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingTimerecordResponse) GetEmployeeKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmployeeKey, true
}

// SetEmployeeKey sets field value
func (o *DailyWorkingTimerecordResponse) SetEmployeeKey(v string) {
	o.EmployeeKey = v
}

// GetTimeRecord returns the TimeRecord field value
func (o *DailyWorkingTimerecordResponse) GetTimeRecord() []DailyWorkingTimerecordResponseTimeRecordInner {
	if o == nil {
		var ret []DailyWorkingTimerecordResponseTimeRecordInner
		return ret
	}

	return o.TimeRecord
}

// GetTimeRecordOk returns a tuple with the TimeRecord field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingTimerecordResponse) GetTimeRecordOk() ([]DailyWorkingTimerecordResponseTimeRecordInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeRecord, true
}

// SetTimeRecord sets field value
func (o *DailyWorkingTimerecordResponse) SetTimeRecord(v []DailyWorkingTimerecordResponseTimeRecordInner) {
	o.TimeRecord = v
}

// GetCurrentDateEmployee returns the CurrentDateEmployee field value if set, zero value otherwise.
func (o *DailyWorkingTimerecordResponse) GetCurrentDateEmployee() DailyWorkingResponseCurrentDateEmployee {
	if o == nil || IsNil(o.CurrentDateEmployee) {
		var ret DailyWorkingResponseCurrentDateEmployee
		return ret
	}
	return *o.CurrentDateEmployee
}

// GetCurrentDateEmployeeOk returns a tuple with the CurrentDateEmployee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DailyWorkingTimerecordResponse) GetCurrentDateEmployeeOk() (*DailyWorkingResponseCurrentDateEmployee, bool) {
	if o == nil || IsNil(o.CurrentDateEmployee) {
		return nil, false
	}
	return o.CurrentDateEmployee, true
}

// HasCurrentDateEmployee returns a boolean if a field has been set.
func (o *DailyWorkingTimerecordResponse) HasCurrentDateEmployee() bool {
	if o != nil && !IsNil(o.CurrentDateEmployee) {
		return true
	}

	return false
}

// SetCurrentDateEmployee gets a reference to the given DailyWorkingResponseCurrentDateEmployee and assigns it to the CurrentDateEmployee field.
func (o *DailyWorkingTimerecordResponse) SetCurrentDateEmployee(v DailyWorkingResponseCurrentDateEmployee) {
	o.CurrentDateEmployee = &v
}

func (o DailyWorkingTimerecordResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyWorkingTimerecordResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["employeeKey"] = o.EmployeeKey
	toSerialize["timeRecord"] = o.TimeRecord
	if !IsNil(o.CurrentDateEmployee) {
		toSerialize["currentDateEmployee"] = o.CurrentDateEmployee
	}
	return toSerialize, nil
}

type NullableDailyWorkingTimerecordResponse struct {
	value *DailyWorkingTimerecordResponse
	isSet bool
}

func (v NullableDailyWorkingTimerecordResponse) Get() *DailyWorkingTimerecordResponse {
	return v.value
}

func (v *NullableDailyWorkingTimerecordResponse) Set(val *DailyWorkingTimerecordResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyWorkingTimerecordResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyWorkingTimerecordResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyWorkingTimerecordResponse(val *DailyWorkingTimerecordResponse) *NullableDailyWorkingTimerecordResponse {
	return &NullableDailyWorkingTimerecordResponse{value: val, isSet: true}
}

func (v NullableDailyWorkingTimerecordResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyWorkingTimerecordResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


