/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetSchedules200ResponseScheduleRequestsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200ResponseScheduleRequestsInner{}

// GetSchedules200ResponseScheduleRequestsInner struct for GetSchedules200ResponseScheduleRequestsInner
type GetSchedules200ResponseScheduleRequestsInner struct {
	// 対象日
	Date string `json:"date"`
	// 申請日
	RequestedDate string `json:"requestedDate"`
	// 従業員識別キー（従業員コードが変更されても不変）
	EmployeeKey string `json:"employeeKey"`
	// 申請識別キー
	RequestKey string `json:"requestKey"`
	Applicant GetSchedules200ResponseScheduleRequestsInnerApplicant `json:"applicant"`
	// 申請ステータス（applying 申請中　rejected： 棄却　approved： 承認）
	Status string `json:"status"`
	// 現在の承認フローレベル（１～５）
	CurrentFlow int32 `json:"currentFlow"`
	// 最終更新管理者識別キー
	LastModifiedAdministratorKey string `json:"lastModifiedAdministratorKey"`
	// 申請メッセージ
	Message string `json:"message"`
	// 管理者コメント
	AdminComment string `json:"adminComment"`
	Requested GetSchedules200ResponseScheduleRequestsInnerRequested `json:"requested"`
	Current GetSchedules200ResponseScheduleRequestsInnerRequested `json:"current"`
	// スケジュールパターンコード
	SchedulePatternCode *string `json:"schedulePatternCode,omitempty"`
	// スケジュールパターン名
	SchedulePatternName *string `json:"schedulePatternName,omitempty"`
	// 勤務開始刻限
	WorkFixedStart *time.Time `json:"workFixedStart,omitempty"`
	// 勤務終了刻限
	WorkFixedEnd *time.Time `json:"workFixedEnd,omitempty"`
	// 備考
	Note *string `json:"note,omitempty"`
	Flow *GetSchedules200ResponseScheduleRequestsInnerFlow `json:"flow,omitempty"`
}

// NewGetSchedules200ResponseScheduleRequestsInner instantiates a new GetSchedules200ResponseScheduleRequestsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200ResponseScheduleRequestsInner(date string, requestedDate string, employeeKey string, requestKey string, applicant GetSchedules200ResponseScheduleRequestsInnerApplicant, status string, currentFlow int32, lastModifiedAdministratorKey string, message string, adminComment string, requested GetSchedules200ResponseScheduleRequestsInnerRequested, current GetSchedules200ResponseScheduleRequestsInnerRequested) *GetSchedules200ResponseScheduleRequestsInner {
	this := GetSchedules200ResponseScheduleRequestsInner{}
	this.Date = date
	this.RequestedDate = requestedDate
	this.EmployeeKey = employeeKey
	this.RequestKey = requestKey
	this.Applicant = applicant
	this.Status = status
	this.CurrentFlow = currentFlow
	this.LastModifiedAdministratorKey = lastModifiedAdministratorKey
	this.Message = message
	this.AdminComment = adminComment
	this.Requested = requested
	this.Current = current
	return &this
}

// NewGetSchedules200ResponseScheduleRequestsInnerWithDefaults instantiates a new GetSchedules200ResponseScheduleRequestsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseScheduleRequestsInnerWithDefaults() *GetSchedules200ResponseScheduleRequestsInner {
	this := GetSchedules200ResponseScheduleRequestsInner{}
	return &this
}

// GetDate returns the Date field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetDate(v string) {
	o.Date = v
}

// GetRequestedDate returns the RequestedDate field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetRequestedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedDate
}

// GetRequestedDateOk returns a tuple with the RequestedDate field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetRequestedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedDate, true
}

// SetRequestedDate sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetRequestedDate(v string) {
	o.RequestedDate = v
}

// GetEmployeeKey returns the EmployeeKey field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetEmployeeKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmployeeKey
}

// GetEmployeeKeyOk returns a tuple with the EmployeeKey field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetEmployeeKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmployeeKey, true
}

// SetEmployeeKey sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetEmployeeKey(v string) {
	o.EmployeeKey = v
}

// GetRequestKey returns the RequestKey field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetRequestKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestKey
}

// GetRequestKeyOk returns a tuple with the RequestKey field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetRequestKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestKey, true
}

// SetRequestKey sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetRequestKey(v string) {
	o.RequestKey = v
}

// GetApplicant returns the Applicant field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetApplicant() GetSchedules200ResponseScheduleRequestsInnerApplicant {
	if o == nil {
		var ret GetSchedules200ResponseScheduleRequestsInnerApplicant
		return ret
	}

	return o.Applicant
}

// GetApplicantOk returns a tuple with the Applicant field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetApplicantOk() (*GetSchedules200ResponseScheduleRequestsInnerApplicant, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Applicant, true
}

// SetApplicant sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetApplicant(v GetSchedules200ResponseScheduleRequestsInnerApplicant) {
	o.Applicant = v
}

// GetStatus returns the Status field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetStatus(v string) {
	o.Status = v
}

// GetCurrentFlow returns the CurrentFlow field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetCurrentFlow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentFlow
}

// GetCurrentFlowOk returns a tuple with the CurrentFlow field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetCurrentFlowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentFlow, true
}

// SetCurrentFlow sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetCurrentFlow(v int32) {
	o.CurrentFlow = v
}

// GetLastModifiedAdministratorKey returns the LastModifiedAdministratorKey field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetLastModifiedAdministratorKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastModifiedAdministratorKey
}

// GetLastModifiedAdministratorKeyOk returns a tuple with the LastModifiedAdministratorKey field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetLastModifiedAdministratorKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModifiedAdministratorKey, true
}

// SetLastModifiedAdministratorKey sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetLastModifiedAdministratorKey(v string) {
	o.LastModifiedAdministratorKey = v
}

// GetMessage returns the Message field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetMessage(v string) {
	o.Message = v
}

// GetAdminComment returns the AdminComment field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetAdminComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdminComment
}

// GetAdminCommentOk returns a tuple with the AdminComment field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetAdminCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdminComment, true
}

// SetAdminComment sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetAdminComment(v string) {
	o.AdminComment = v
}

// GetRequested returns the Requested field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetRequested() GetSchedules200ResponseScheduleRequestsInnerRequested {
	if o == nil {
		var ret GetSchedules200ResponseScheduleRequestsInnerRequested
		return ret
	}

	return o.Requested
}

// GetRequestedOk returns a tuple with the Requested field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetRequestedOk() (*GetSchedules200ResponseScheduleRequestsInnerRequested, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Requested, true
}

// SetRequested sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetRequested(v GetSchedules200ResponseScheduleRequestsInnerRequested) {
	o.Requested = v
}

// GetCurrent returns the Current field value
func (o *GetSchedules200ResponseScheduleRequestsInner) GetCurrent() GetSchedules200ResponseScheduleRequestsInnerRequested {
	if o == nil {
		var ret GetSchedules200ResponseScheduleRequestsInnerRequested
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetCurrentOk() (*GetSchedules200ResponseScheduleRequestsInnerRequested, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *GetSchedules200ResponseScheduleRequestsInner) SetCurrent(v GetSchedules200ResponseScheduleRequestsInnerRequested) {
	o.Current = v
}

// GetSchedulePatternCode returns the SchedulePatternCode field value if set, zero value otherwise.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetSchedulePatternCode() string {
	if o == nil || IsNil(o.SchedulePatternCode) {
		var ret string
		return ret
	}
	return *o.SchedulePatternCode
}

// GetSchedulePatternCodeOk returns a tuple with the SchedulePatternCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetSchedulePatternCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SchedulePatternCode) {
		return nil, false
	}
	return o.SchedulePatternCode, true
}

// HasSchedulePatternCode returns a boolean if a field has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) HasSchedulePatternCode() bool {
	if o != nil && !IsNil(o.SchedulePatternCode) {
		return true
	}

	return false
}

// SetSchedulePatternCode gets a reference to the given string and assigns it to the SchedulePatternCode field.
func (o *GetSchedules200ResponseScheduleRequestsInner) SetSchedulePatternCode(v string) {
	o.SchedulePatternCode = &v
}

// GetSchedulePatternName returns the SchedulePatternName field value if set, zero value otherwise.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetSchedulePatternName() string {
	if o == nil || IsNil(o.SchedulePatternName) {
		var ret string
		return ret
	}
	return *o.SchedulePatternName
}

// GetSchedulePatternNameOk returns a tuple with the SchedulePatternName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetSchedulePatternNameOk() (*string, bool) {
	if o == nil || IsNil(o.SchedulePatternName) {
		return nil, false
	}
	return o.SchedulePatternName, true
}

// HasSchedulePatternName returns a boolean if a field has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) HasSchedulePatternName() bool {
	if o != nil && !IsNil(o.SchedulePatternName) {
		return true
	}

	return false
}

// SetSchedulePatternName gets a reference to the given string and assigns it to the SchedulePatternName field.
func (o *GetSchedules200ResponseScheduleRequestsInner) SetSchedulePatternName(v string) {
	o.SchedulePatternName = &v
}

// GetWorkFixedStart returns the WorkFixedStart field value if set, zero value otherwise.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetWorkFixedStart() time.Time {
	if o == nil || IsNil(o.WorkFixedStart) {
		var ret time.Time
		return ret
	}
	return *o.WorkFixedStart
}

// GetWorkFixedStartOk returns a tuple with the WorkFixedStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetWorkFixedStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.WorkFixedStart) {
		return nil, false
	}
	return o.WorkFixedStart, true
}

// HasWorkFixedStart returns a boolean if a field has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) HasWorkFixedStart() bool {
	if o != nil && !IsNil(o.WorkFixedStart) {
		return true
	}

	return false
}

// SetWorkFixedStart gets a reference to the given time.Time and assigns it to the WorkFixedStart field.
func (o *GetSchedules200ResponseScheduleRequestsInner) SetWorkFixedStart(v time.Time) {
	o.WorkFixedStart = &v
}

// GetWorkFixedEnd returns the WorkFixedEnd field value if set, zero value otherwise.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetWorkFixedEnd() time.Time {
	if o == nil || IsNil(o.WorkFixedEnd) {
		var ret time.Time
		return ret
	}
	return *o.WorkFixedEnd
}

// GetWorkFixedEndOk returns a tuple with the WorkFixedEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetWorkFixedEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.WorkFixedEnd) {
		return nil, false
	}
	return o.WorkFixedEnd, true
}

// HasWorkFixedEnd returns a boolean if a field has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) HasWorkFixedEnd() bool {
	if o != nil && !IsNil(o.WorkFixedEnd) {
		return true
	}

	return false
}

// SetWorkFixedEnd gets a reference to the given time.Time and assigns it to the WorkFixedEnd field.
func (o *GetSchedules200ResponseScheduleRequestsInner) SetWorkFixedEnd(v time.Time) {
	o.WorkFixedEnd = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *GetSchedules200ResponseScheduleRequestsInner) SetNote(v string) {
	o.Note = &v
}

// GetFlow returns the Flow field value if set, zero value otherwise.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetFlow() GetSchedules200ResponseScheduleRequestsInnerFlow {
	if o == nil || IsNil(o.Flow) {
		var ret GetSchedules200ResponseScheduleRequestsInnerFlow
		return ret
	}
	return *o.Flow
}

// GetFlowOk returns a tuple with the Flow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) GetFlowOk() (*GetSchedules200ResponseScheduleRequestsInnerFlow, bool) {
	if o == nil || IsNil(o.Flow) {
		return nil, false
	}
	return o.Flow, true
}

// HasFlow returns a boolean if a field has been set.
func (o *GetSchedules200ResponseScheduleRequestsInner) HasFlow() bool {
	if o != nil && !IsNil(o.Flow) {
		return true
	}

	return false
}

// SetFlow gets a reference to the given GetSchedules200ResponseScheduleRequestsInnerFlow and assigns it to the Flow field.
func (o *GetSchedules200ResponseScheduleRequestsInner) SetFlow(v GetSchedules200ResponseScheduleRequestsInnerFlow) {
	o.Flow = &v
}

func (o GetSchedules200ResponseScheduleRequestsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200ResponseScheduleRequestsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["requestedDate"] = o.RequestedDate
	toSerialize["employeeKey"] = o.EmployeeKey
	toSerialize["requestKey"] = o.RequestKey
	toSerialize["applicant"] = o.Applicant
	toSerialize["status"] = o.Status
	toSerialize["currentFlow"] = o.CurrentFlow
	toSerialize["lastModifiedAdministratorKey"] = o.LastModifiedAdministratorKey
	toSerialize["message"] = o.Message
	toSerialize["adminComment"] = o.AdminComment
	toSerialize["requested"] = o.Requested
	toSerialize["current"] = o.Current
	if !IsNil(o.SchedulePatternCode) {
		toSerialize["schedulePatternCode"] = o.SchedulePatternCode
	}
	if !IsNil(o.SchedulePatternName) {
		toSerialize["schedulePatternName"] = o.SchedulePatternName
	}
	if !IsNil(o.WorkFixedStart) {
		toSerialize["workFixedStart"] = o.WorkFixedStart
	}
	if !IsNil(o.WorkFixedEnd) {
		toSerialize["workFixedEnd"] = o.WorkFixedEnd
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.Flow) {
		toSerialize["flow"] = o.Flow
	}
	return toSerialize, nil
}

type NullableGetSchedules200ResponseScheduleRequestsInner struct {
	value *GetSchedules200ResponseScheduleRequestsInner
	isSet bool
}

func (v NullableGetSchedules200ResponseScheduleRequestsInner) Get() *GetSchedules200ResponseScheduleRequestsInner {
	return v.value
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInner) Set(val *GetSchedules200ResponseScheduleRequestsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200ResponseScheduleRequestsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200ResponseScheduleRequestsInner(val *GetSchedules200ResponseScheduleRequestsInner) *NullableGetSchedules200ResponseScheduleRequestsInner {
	return &NullableGetSchedules200ResponseScheduleRequestsInner{value: val, isSet: true}
}

func (v NullableGetSchedules200ResponseScheduleRequestsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


