/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee{}

// GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee 今日時点の従業員データ
type GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee struct {
	// 所属コード
	DivisionCode string `json:"divisionCode"`
	// 所属名
	DivisionName string `json:"divisionName"`
	// 性別（no_selected： 選択しない　male： 男性　female： 女性）
	Gender string `json:"gender"`
	// 雇用区分コード
	TypeCode string `json:"typeCode"`
	// 雇用区分名
	TypeName string `json:"typeName"`
	// 従業員コード
	Code string `json:"code"`
	// 姓
	LastName string `json:"lastName"`
	// 名
	FirstName string `json:"firstName"`
	// 姓（カナ）
	LastNamePhonetics string `json:"lastNamePhonetics"`
	// 名（カナ）
	FirstNamePhonetics string `json:"firstNamePhonetics"`
	// 従業員グループ情報
	EmployeeGroups []GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeEmployeeGroupsInner `json:"employeeGroups"`
}

// NewGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee instantiates a new GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee(divisionCode string, divisionName string, gender string, typeCode string, typeName string, code string, lastName string, firstName string, lastNamePhonetics string, firstNamePhonetics string, employeeGroups []GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeEmployeeGroupsInner) *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee {
	this := GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee{}
	this.DivisionCode = divisionCode
	this.DivisionName = divisionName
	this.Gender = gender
	this.TypeCode = typeCode
	this.TypeName = typeName
	this.Code = code
	this.LastName = lastName
	this.FirstName = firstName
	this.LastNamePhonetics = lastNamePhonetics
	this.FirstNamePhonetics = firstNamePhonetics
	this.EmployeeGroups = employeeGroups
	return &this
}

// NewGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeWithDefaults instantiates a new GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeWithDefaults() *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee {
	this := GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee{}
	return &this
}

// GetDivisionCode returns the DivisionCode field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetDivisionCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DivisionCode
}

// GetDivisionCodeOk returns a tuple with the DivisionCode field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetDivisionCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DivisionCode, true
}

// SetDivisionCode sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetDivisionCode(v string) {
	o.DivisionCode = v
}

// GetDivisionName returns the DivisionName field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetDivisionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DivisionName
}

// GetDivisionNameOk returns a tuple with the DivisionName field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetDivisionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DivisionName, true
}

// SetDivisionName sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetDivisionName(v string) {
	o.DivisionName = v
}

// GetGender returns the Gender field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetGender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetGender(v string) {
	o.Gender = v
}

// GetTypeCode returns the TypeCode field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetTypeCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeCode
}

// GetTypeCodeOk returns a tuple with the TypeCode field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetTypeCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeCode, true
}

// SetTypeCode sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetTypeCode(v string) {
	o.TypeCode = v
}

// GetTypeName returns the TypeName field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeName
}

// GetTypeNameOk returns a tuple with the TypeName field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeName, true
}

// SetTypeName sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetTypeName(v string) {
	o.TypeName = v
}

// GetCode returns the Code field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetCode(v string) {
	o.Code = v
}

// GetLastName returns the LastName field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetLastName(v string) {
	o.LastName = v
}

// GetFirstName returns the FirstName field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastNamePhonetics returns the LastNamePhonetics field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetLastNamePhonetics() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastNamePhonetics
}

// GetLastNamePhoneticsOk returns a tuple with the LastNamePhonetics field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetLastNamePhoneticsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastNamePhonetics, true
}

// SetLastNamePhonetics sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetLastNamePhonetics(v string) {
	o.LastNamePhonetics = v
}

// GetFirstNamePhonetics returns the FirstNamePhonetics field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetFirstNamePhonetics() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstNamePhonetics
}

// GetFirstNamePhoneticsOk returns a tuple with the FirstNamePhonetics field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetFirstNamePhoneticsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstNamePhonetics, true
}

// SetFirstNamePhonetics sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetFirstNamePhonetics(v string) {
	o.FirstNamePhonetics = v
}

// GetEmployeeGroups returns the EmployeeGroups field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetEmployeeGroups() []GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeEmployeeGroupsInner {
	if o == nil {
		var ret []GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeEmployeeGroupsInner
		return ret
	}

	return o.EmployeeGroups
}

// GetEmployeeGroupsOk returns a tuple with the EmployeeGroups field value
// and a boolean to check if the value has been set.
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) GetEmployeeGroupsOk() ([]GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeEmployeeGroupsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmployeeGroups, true
}

// SetEmployeeGroups sets field value
func (o *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) SetEmployeeGroups(v []GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployeeEmployeeGroupsInner) {
	o.EmployeeGroups = v
}

func (o GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["divisionCode"] = o.DivisionCode
	toSerialize["divisionName"] = o.DivisionName
	toSerialize["gender"] = o.Gender
	toSerialize["typeCode"] = o.TypeCode
	toSerialize["typeName"] = o.TypeName
	toSerialize["code"] = o.Code
	toSerialize["lastName"] = o.LastName
	toSerialize["firstName"] = o.FirstName
	toSerialize["lastNamePhonetics"] = o.LastNamePhonetics
	toSerialize["firstNamePhonetics"] = o.FirstNamePhonetics
	toSerialize["employeeGroups"] = o.EmployeeGroups
	return toSerialize, nil
}

type NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee struct {
	value *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee
	isSet bool
}

func (v NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) Get() *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee {
	return v.value
}

func (v *NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) Set(val *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee(val *GetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) *NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee {
	return &NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee{value: val, isSet: true}
}

func (v NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDailyWorkingTimerecords200ResponseInnerCurrentDateEmployee) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


