/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEmployeeGroups200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmployeeGroups200ResponseInner{}

// GetEmployeeGroups200ResponseInner struct for GetEmployeeGroups200ResponseInner
type GetEmployeeGroups200ResponseInner struct {
	// 従業員グループコード
	Code string `json:"code"`
	// 従業員グループ名
	Name string `json:"name"`
	Category *GetEmployeeGroups200ResponseInnerCategory `json:"category,omitempty"`
}

// NewGetEmployeeGroups200ResponseInner instantiates a new GetEmployeeGroups200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmployeeGroups200ResponseInner(code string, name string) *GetEmployeeGroups200ResponseInner {
	this := GetEmployeeGroups200ResponseInner{}
	this.Code = code
	this.Name = name
	return &this
}

// NewGetEmployeeGroups200ResponseInnerWithDefaults instantiates a new GetEmployeeGroups200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmployeeGroups200ResponseInnerWithDefaults() *GetEmployeeGroups200ResponseInner {
	this := GetEmployeeGroups200ResponseInner{}
	return &this
}

// GetCode returns the Code field value
func (o *GetEmployeeGroups200ResponseInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetEmployeeGroups200ResponseInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetEmployeeGroups200ResponseInner) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *GetEmployeeGroups200ResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetEmployeeGroups200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetEmployeeGroups200ResponseInner) SetName(v string) {
	o.Name = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *GetEmployeeGroups200ResponseInner) GetCategory() GetEmployeeGroups200ResponseInnerCategory {
	if o == nil || IsNil(o.Category) {
		var ret GetEmployeeGroups200ResponseInnerCategory
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmployeeGroups200ResponseInner) GetCategoryOk() (*GetEmployeeGroups200ResponseInnerCategory, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *GetEmployeeGroups200ResponseInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given GetEmployeeGroups200ResponseInnerCategory and assigns it to the Category field.
func (o *GetEmployeeGroups200ResponseInner) SetCategory(v GetEmployeeGroups200ResponseInnerCategory) {
	o.Category = &v
}

func (o GetEmployeeGroups200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmployeeGroups200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	return toSerialize, nil
}

type NullableGetEmployeeGroups200ResponseInner struct {
	value *GetEmployeeGroups200ResponseInner
	isSet bool
}

func (v NullableGetEmployeeGroups200ResponseInner) Get() *GetEmployeeGroups200ResponseInner {
	return v.value
}

func (v *NullableGetEmployeeGroups200ResponseInner) Set(val *GetEmployeeGroups200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmployeeGroups200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmployeeGroups200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmployeeGroups200ResponseInner(val *GetEmployeeGroups200ResponseInner) *NullableGetEmployeeGroups200ResponseInner {
	return &NullableGetEmployeeGroups200ResponseInner{value: val, isSet: true}
}

func (v NullableGetEmployeeGroups200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmployeeGroups200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


