/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RefreshAccessToken201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshAccessToken201Response{}

// RefreshAccessToken201Response struct for RefreshAccessToken201Response
type RefreshAccessToken201Response struct {
	// refreshed access token
	Token string `json:"token"`
}

// NewRefreshAccessToken201Response instantiates a new RefreshAccessToken201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshAccessToken201Response(token string) *RefreshAccessToken201Response {
	this := RefreshAccessToken201Response{}
	this.Token = token
	return &this
}

// NewRefreshAccessToken201ResponseWithDefaults instantiates a new RefreshAccessToken201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshAccessToken201ResponseWithDefaults() *RefreshAccessToken201Response {
	this := RefreshAccessToken201Response{}
	return &this
}

// GetToken returns the Token field value
func (o *RefreshAccessToken201Response) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *RefreshAccessToken201Response) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *RefreshAccessToken201Response) SetToken(v string) {
	o.Token = v
}

func (o RefreshAccessToken201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshAccessToken201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

type NullableRefreshAccessToken201Response struct {
	value *RefreshAccessToken201Response
	isSet bool
}

func (v NullableRefreshAccessToken201Response) Get() *RefreshAccessToken201Response {
	return v.value
}

func (v *NullableRefreshAccessToken201Response) Set(val *RefreshAccessToken201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshAccessToken201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshAccessToken201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshAccessToken201Response(val *RefreshAccessToken201Response) *NullableRefreshAccessToken201Response {
	return &NullableRefreshAccessToken201Response{value: val, isSet: true}
}

func (v NullableRefreshAccessToken201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshAccessToken201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


