/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner{}

// GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner struct for GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner
type GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner struct {
	// 休憩開始予定
	Start time.Time `json:"start"`
	// 休憩終了予定
	End time.Time `json:"end"`
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner(start time.Time, end time.Time) *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner {
	this := GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner{}
	this.Start = start
	this.End = end
	return &this
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInnerWithDefaults instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInnerWithDefaults() *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner {
	this := GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner{}
	return &this
}

// GetStart returns the Start field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) SetEnd(v time.Time) {
	o.End = v
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

type NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner struct {
	value *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner
	isSet bool
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) Get() *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner {
	return v.value
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) Set(val *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner(val *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner {
	return &NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner{value: val, isSet: true}
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


