/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkingTypeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkingTypeResponse{}

// WorkingTypeResponse struct for WorkingTypeResponse
type WorkingTypeResponse struct {
	// 雇用区分コード
	Code string `json:"code"`
	// 雇用区分名
	Name string `json:"name"`
}

// NewWorkingTypeResponse instantiates a new WorkingTypeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkingTypeResponse(code string, name string) *WorkingTypeResponse {
	this := WorkingTypeResponse{}
	this.Code = code
	this.Name = name
	return &this
}

// NewWorkingTypeResponseWithDefaults instantiates a new WorkingTypeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkingTypeResponseWithDefaults() *WorkingTypeResponse {
	this := WorkingTypeResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *WorkingTypeResponse) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *WorkingTypeResponse) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *WorkingTypeResponse) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *WorkingTypeResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkingTypeResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkingTypeResponse) SetName(v string) {
	o.Name = v
}

func (o WorkingTypeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkingTypeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableWorkingTypeResponse struct {
	value *WorkingTypeResponse
	isSet bool
}

func (v NullableWorkingTypeResponse) Get() *WorkingTypeResponse {
	return v.value
}

func (v *NullableWorkingTypeResponse) Set(val *WorkingTypeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkingTypeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkingTypeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkingTypeResponse(val *WorkingTypeResponse) *NullableWorkingTypeResponse {
	return &NullableWorkingTypeResponse{value: val, isSet: true}
}

func (v NullableWorkingTypeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkingTypeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


