/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCompany200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCompany200Response{}

// GetCompany200Response struct for GetCompany200Response
type GetCompany200Response struct {
	// 企業識別キー
	Key string `json:"key"`
	// 企業コード
	Code string `json:"code"`
	// 企業名
	Name string `json:"name"`
	// ホスト名
	Host string `json:"host"`
	// 事業年度開始日
	BusinessYearStartDate string `json:"businessYearStartDate"`
	Settings GetCompany200ResponseSettings `json:"settings"`
}

// NewGetCompany200Response instantiates a new GetCompany200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCompany200Response(key string, code string, name string, host string, businessYearStartDate string, settings GetCompany200ResponseSettings) *GetCompany200Response {
	this := GetCompany200Response{}
	this.Key = key
	this.Code = code
	this.Name = name
	this.Host = host
	this.BusinessYearStartDate = businessYearStartDate
	this.Settings = settings
	return &this
}

// NewGetCompany200ResponseWithDefaults instantiates a new GetCompany200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCompany200ResponseWithDefaults() *GetCompany200Response {
	this := GetCompany200Response{}
	return &this
}

// GetKey returns the Key field value
func (o *GetCompany200Response) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *GetCompany200Response) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *GetCompany200Response) SetKey(v string) {
	o.Key = v
}

// GetCode returns the Code field value
func (o *GetCompany200Response) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetCompany200Response) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetCompany200Response) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *GetCompany200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetCompany200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetCompany200Response) SetName(v string) {
	o.Name = v
}

// GetHost returns the Host field value
func (o *GetCompany200Response) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *GetCompany200Response) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *GetCompany200Response) SetHost(v string) {
	o.Host = v
}

// GetBusinessYearStartDate returns the BusinessYearStartDate field value
func (o *GetCompany200Response) GetBusinessYearStartDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessYearStartDate
}

// GetBusinessYearStartDateOk returns a tuple with the BusinessYearStartDate field value
// and a boolean to check if the value has been set.
func (o *GetCompany200Response) GetBusinessYearStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessYearStartDate, true
}

// SetBusinessYearStartDate sets field value
func (o *GetCompany200Response) SetBusinessYearStartDate(v string) {
	o.BusinessYearStartDate = v
}

// GetSettings returns the Settings field value
func (o *GetCompany200Response) GetSettings() GetCompany200ResponseSettings {
	if o == nil {
		var ret GetCompany200ResponseSettings
		return ret
	}

	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value
// and a boolean to check if the value has been set.
func (o *GetCompany200Response) GetSettingsOk() (*GetCompany200ResponseSettings, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Settings, true
}

// SetSettings sets field value
func (o *GetCompany200Response) SetSettings(v GetCompany200ResponseSettings) {
	o.Settings = v
}

func (o GetCompany200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCompany200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	toSerialize["host"] = o.Host
	toSerialize["businessYearStartDate"] = o.BusinessYearStartDate
	toSerialize["settings"] = o.Settings
	return toSerialize, nil
}

type NullableGetCompany200Response struct {
	value *GetCompany200Response
	isSet bool
}

func (v NullableGetCompany200Response) Get() *GetCompany200Response {
	return v.value
}

func (v *NullableGetCompany200Response) Set(val *GetCompany200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCompany200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCompany200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCompany200Response(val *GetCompany200Response) *NullableGetCompany200Response {
	return &NullableGetCompany200Response{value: val, isSet: true}
}

func (v NullableGetCompany200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCompany200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


