/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday{}

// GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday struct for GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday
type GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday struct {
	// 休暇区分コード
	Code string `json:"code"`
	// 休暇区分名
	Name string `json:"name"`
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday(code string, name string) *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday {
	this := GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday{}
	this.Code = code
	this.Name = name
	return &this
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHolidayWithDefaults instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHolidayWithDefaults() *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday {
	this := GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday{}
	return &this
}

// GetCode returns the Code field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) SetName(v string) {
	o.Name = v
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday struct {
	value *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday
	isSet bool
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) Get() *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday {
	return v.value
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) Set(val *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday(val *GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday {
	return &NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday{value: val, isSet: true}
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtainedFulltimeHoliday) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


