/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EmployeeEmployeeGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeEmployeeGroupsInner{}

// EmployeeEmployeeGroupsInner struct for EmployeeEmployeeGroupsInner
type EmployeeEmployeeGroupsInner struct {
	// 従業員グループコード
	Code string `json:"code"`
	// 従業員グループ名
	Name string `json:"name"`
}

// NewEmployeeEmployeeGroupsInner instantiates a new EmployeeEmployeeGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeEmployeeGroupsInner(code string, name string) *EmployeeEmployeeGroupsInner {
	this := EmployeeEmployeeGroupsInner{}
	this.Code = code
	this.Name = name
	return &this
}

// NewEmployeeEmployeeGroupsInnerWithDefaults instantiates a new EmployeeEmployeeGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeEmployeeGroupsInnerWithDefaults() *EmployeeEmployeeGroupsInner {
	this := EmployeeEmployeeGroupsInner{}
	return &this
}

// GetCode returns the Code field value
func (o *EmployeeEmployeeGroupsInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *EmployeeEmployeeGroupsInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *EmployeeEmployeeGroupsInner) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *EmployeeEmployeeGroupsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EmployeeEmployeeGroupsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EmployeeEmployeeGroupsInner) SetName(v string) {
	o.Name = v
}

func (o EmployeeEmployeeGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeEmployeeGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableEmployeeEmployeeGroupsInner struct {
	value *EmployeeEmployeeGroupsInner
	isSet bool
}

func (v NullableEmployeeEmployeeGroupsInner) Get() *EmployeeEmployeeGroupsInner {
	return v.value
}

func (v *NullableEmployeeEmployeeGroupsInner) Set(val *EmployeeEmployeeGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeEmployeeGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeEmployeeGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeEmployeeGroupsInner(val *EmployeeEmployeeGroupsInner) *NullableEmployeeEmployeeGroupsInner {
	return &NullableEmployeeEmployeeGroupsInner{value: val, isSet: true}
}

func (v NullableEmployeeEmployeeGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeEmployeeGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


