/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEmployees200ResponseInnerEmployeeGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmployees200ResponseInnerEmployeeGroupsInner{}

// GetEmployees200ResponseInnerEmployeeGroupsInner struct for GetEmployees200ResponseInnerEmployeeGroupsInner
type GetEmployees200ResponseInnerEmployeeGroupsInner struct {
	// 従業員グループコード
	Code string `json:"code"`
	// 従業員グループ名
	Name string `json:"name"`
}

// NewGetEmployees200ResponseInnerEmployeeGroupsInner instantiates a new GetEmployees200ResponseInnerEmployeeGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmployees200ResponseInnerEmployeeGroupsInner(code string, name string) *GetEmployees200ResponseInnerEmployeeGroupsInner {
	this := GetEmployees200ResponseInnerEmployeeGroupsInner{}
	this.Code = code
	this.Name = name
	return &this
}

// NewGetEmployees200ResponseInnerEmployeeGroupsInnerWithDefaults instantiates a new GetEmployees200ResponseInnerEmployeeGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmployees200ResponseInnerEmployeeGroupsInnerWithDefaults() *GetEmployees200ResponseInnerEmployeeGroupsInner {
	this := GetEmployees200ResponseInnerEmployeeGroupsInner{}
	return &this
}

// GetCode returns the Code field value
func (o *GetEmployees200ResponseInnerEmployeeGroupsInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetEmployees200ResponseInnerEmployeeGroupsInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetEmployees200ResponseInnerEmployeeGroupsInner) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *GetEmployees200ResponseInnerEmployeeGroupsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetEmployees200ResponseInnerEmployeeGroupsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetEmployees200ResponseInnerEmployeeGroupsInner) SetName(v string) {
	o.Name = v
}

func (o GetEmployees200ResponseInnerEmployeeGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmployees200ResponseInnerEmployeeGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableGetEmployees200ResponseInnerEmployeeGroupsInner struct {
	value *GetEmployees200ResponseInnerEmployeeGroupsInner
	isSet bool
}

func (v NullableGetEmployees200ResponseInnerEmployeeGroupsInner) Get() *GetEmployees200ResponseInnerEmployeeGroupsInner {
	return v.value
}

func (v *NullableGetEmployees200ResponseInnerEmployeeGroupsInner) Set(val *GetEmployees200ResponseInnerEmployeeGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmployees200ResponseInnerEmployeeGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmployees200ResponseInnerEmployeeGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmployees200ResponseInnerEmployeeGroupsInner(val *GetEmployees200ResponseInnerEmployeeGroupsInner) *NullableGetEmployees200ResponseInnerEmployeeGroupsInner {
	return &NullableGetEmployees200ResponseInnerEmployeeGroupsInner{value: val, isSet: true}
}

func (v NullableGetEmployees200ResponseInnerEmployeeGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmployees200ResponseInnerEmployeeGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


