/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAdministrators200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAdministrators200ResponseInner{}

// GetAdministrators200ResponseInner struct for GetAdministrators200ResponseInner
type GetAdministrators200ResponseInner struct {
	// 管理者コード
	Code string `json:"code"`
	// 管理者識別キー（管理者コードが変更されても不変）
	Key string `json:"key"`
	// 管理者名
	Name string `json:"name"`
	// メールアドレス
	EmailAddresses *string `json:"emailAddresses,omitempty"`
	AssociatedEmployees *GetAdministrators200ResponseInnerAssociatedEmployees `json:"associatedEmployees,omitempty"`
}

// NewGetAdministrators200ResponseInner instantiates a new GetAdministrators200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAdministrators200ResponseInner(code string, key string, name string) *GetAdministrators200ResponseInner {
	this := GetAdministrators200ResponseInner{}
	this.Code = code
	this.Key = key
	this.Name = name
	return &this
}

// NewGetAdministrators200ResponseInnerWithDefaults instantiates a new GetAdministrators200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAdministrators200ResponseInnerWithDefaults() *GetAdministrators200ResponseInner {
	this := GetAdministrators200ResponseInner{}
	return &this
}

// GetCode returns the Code field value
func (o *GetAdministrators200ResponseInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetAdministrators200ResponseInner) SetCode(v string) {
	o.Code = v
}

// GetKey returns the Key field value
func (o *GetAdministrators200ResponseInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *GetAdministrators200ResponseInner) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *GetAdministrators200ResponseInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetAdministrators200ResponseInner) SetName(v string) {
	o.Name = v
}

// GetEmailAddresses returns the EmailAddresses field value if set, zero value otherwise.
func (o *GetAdministrators200ResponseInner) GetEmailAddresses() string {
	if o == nil || IsNil(o.EmailAddresses) {
		var ret string
		return ret
	}
	return *o.EmailAddresses
}

// GetEmailAddressesOk returns a tuple with the EmailAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInner) GetEmailAddressesOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddresses) {
		return nil, false
	}
	return o.EmailAddresses, true
}

// HasEmailAddresses returns a boolean if a field has been set.
func (o *GetAdministrators200ResponseInner) HasEmailAddresses() bool {
	if o != nil && !IsNil(o.EmailAddresses) {
		return true
	}

	return false
}

// SetEmailAddresses gets a reference to the given string and assigns it to the EmailAddresses field.
func (o *GetAdministrators200ResponseInner) SetEmailAddresses(v string) {
	o.EmailAddresses = &v
}

// GetAssociatedEmployees returns the AssociatedEmployees field value if set, zero value otherwise.
func (o *GetAdministrators200ResponseInner) GetAssociatedEmployees() GetAdministrators200ResponseInnerAssociatedEmployees {
	if o == nil || IsNil(o.AssociatedEmployees) {
		var ret GetAdministrators200ResponseInnerAssociatedEmployees
		return ret
	}
	return *o.AssociatedEmployees
}

// GetAssociatedEmployeesOk returns a tuple with the AssociatedEmployees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInner) GetAssociatedEmployeesOk() (*GetAdministrators200ResponseInnerAssociatedEmployees, bool) {
	if o == nil || IsNil(o.AssociatedEmployees) {
		return nil, false
	}
	return o.AssociatedEmployees, true
}

// HasAssociatedEmployees returns a boolean if a field has been set.
func (o *GetAdministrators200ResponseInner) HasAssociatedEmployees() bool {
	if o != nil && !IsNil(o.AssociatedEmployees) {
		return true
	}

	return false
}

// SetAssociatedEmployees gets a reference to the given GetAdministrators200ResponseInnerAssociatedEmployees and assigns it to the AssociatedEmployees field.
func (o *GetAdministrators200ResponseInner) SetAssociatedEmployees(v GetAdministrators200ResponseInnerAssociatedEmployees) {
	o.AssociatedEmployees = &v
}

func (o GetAdministrators200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAdministrators200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	if !IsNil(o.EmailAddresses) {
		toSerialize["emailAddresses"] = o.EmailAddresses
	}
	if !IsNil(o.AssociatedEmployees) {
		toSerialize["associatedEmployees"] = o.AssociatedEmployees
	}
	return toSerialize, nil
}

type NullableGetAdministrators200ResponseInner struct {
	value *GetAdministrators200ResponseInner
	isSet bool
}

func (v NullableGetAdministrators200ResponseInner) Get() *GetAdministrators200ResponseInner {
	return v.value
}

func (v *NullableGetAdministrators200ResponseInner) Set(val *GetAdministrators200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAdministrators200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAdministrators200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAdministrators200ResponseInner(val *GetAdministrators200ResponseInner) *NullableGetAdministrators200ResponseInner {
	return &NullableGetAdministrators200ResponseInner{value: val, isSet: true}
}

func (v NullableGetAdministrators200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAdministrators200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


