/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAdministrators200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAdministrators200Response{}

// GetAdministrators200Response struct for GetAdministrators200Response
type GetAdministrators200Response struct {
	// 管理者コード
	Code string `json:"code"`
	// 管理者識別キー（管理者コードが変更されても不変）
	Key string `json:"key"`
	// 管理者名
	Name string `json:"name"`
	// メールアドレス
	EmailAddresses *string `json:"emailAddresses,omitempty"`
	AssociatedEmployees *GetAdministrators200ResponseAssociatedEmployees `json:"associatedEmployees,omitempty"`
}

// NewGetAdministrators200Response instantiates a new GetAdministrators200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAdministrators200Response(code string, key string, name string) *GetAdministrators200Response {
	this := GetAdministrators200Response{}
	this.Code = code
	this.Key = key
	this.Name = name
	return &this
}

// NewGetAdministrators200ResponseWithDefaults instantiates a new GetAdministrators200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAdministrators200ResponseWithDefaults() *GetAdministrators200Response {
	this := GetAdministrators200Response{}
	return &this
}

// GetCode returns the Code field value
func (o *GetAdministrators200Response) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200Response) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetAdministrators200Response) SetCode(v string) {
	o.Code = v
}

// GetKey returns the Key field value
func (o *GetAdministrators200Response) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200Response) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *GetAdministrators200Response) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *GetAdministrators200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetAdministrators200Response) SetName(v string) {
	o.Name = v
}

// GetEmailAddresses returns the EmailAddresses field value if set, zero value otherwise.
func (o *GetAdministrators200Response) GetEmailAddresses() string {
	if o == nil || IsNil(o.EmailAddresses) {
		var ret string
		return ret
	}
	return *o.EmailAddresses
}

// GetEmailAddressesOk returns a tuple with the EmailAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdministrators200Response) GetEmailAddressesOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddresses) {
		return nil, false
	}
	return o.EmailAddresses, true
}

// HasEmailAddresses returns a boolean if a field has been set.
func (o *GetAdministrators200Response) HasEmailAddresses() bool {
	if o != nil && !IsNil(o.EmailAddresses) {
		return true
	}

	return false
}

// SetEmailAddresses gets a reference to the given string and assigns it to the EmailAddresses field.
func (o *GetAdministrators200Response) SetEmailAddresses(v string) {
	o.EmailAddresses = &v
}

// GetAssociatedEmployees returns the AssociatedEmployees field value if set, zero value otherwise.
func (o *GetAdministrators200Response) GetAssociatedEmployees() GetAdministrators200ResponseAssociatedEmployees {
	if o == nil || IsNil(o.AssociatedEmployees) {
		var ret GetAdministrators200ResponseAssociatedEmployees
		return ret
	}
	return *o.AssociatedEmployees
}

// GetAssociatedEmployeesOk returns a tuple with the AssociatedEmployees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdministrators200Response) GetAssociatedEmployeesOk() (*GetAdministrators200ResponseAssociatedEmployees, bool) {
	if o == nil || IsNil(o.AssociatedEmployees) {
		return nil, false
	}
	return o.AssociatedEmployees, true
}

// HasAssociatedEmployees returns a boolean if a field has been set.
func (o *GetAdministrators200Response) HasAssociatedEmployees() bool {
	if o != nil && !IsNil(o.AssociatedEmployees) {
		return true
	}

	return false
}

// SetAssociatedEmployees gets a reference to the given GetAdministrators200ResponseAssociatedEmployees and assigns it to the AssociatedEmployees field.
func (o *GetAdministrators200Response) SetAssociatedEmployees(v GetAdministrators200ResponseAssociatedEmployees) {
	o.AssociatedEmployees = &v
}

func (o GetAdministrators200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAdministrators200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	if !IsNil(o.EmailAddresses) {
		toSerialize["emailAddresses"] = o.EmailAddresses
	}
	if !IsNil(o.AssociatedEmployees) {
		toSerialize["associatedEmployees"] = o.AssociatedEmployees
	}
	return toSerialize, nil
}

type NullableGetAdministrators200Response struct {
	value *GetAdministrators200Response
	isSet bool
}

func (v NullableGetAdministrators200Response) Get() *GetAdministrators200Response {
	return v.value
}

func (v *NullableGetAdministrators200Response) Set(val *GetAdministrators200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAdministrators200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAdministrators200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAdministrators200Response(val *GetAdministrators200Response) *NullableGetAdministrators200Response {
	return &NullableGetAdministrators200Response{value: val, isSet: true}
}

func (v NullableGetAdministrators200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAdministrators200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


