/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAdministrators200ResponseInnerAssociatedEmployeesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAdministrators200ResponseInnerAssociatedEmployeesInner{}

// GetAdministrators200ResponseInnerAssociatedEmployeesInner 割当従業員
type GetAdministrators200ResponseInnerAssociatedEmployeesInner struct {
	// 従業員コード
	Code string `json:"code"`
	// 従業員識別キー（従業員コードが変更されても不変）
	Key string `json:"key"`
	// 姓
	LastName string `json:"lastName"`
	// 名
	FirstName string `json:"firstName"`
}

// NewGetAdministrators200ResponseInnerAssociatedEmployeesInner instantiates a new GetAdministrators200ResponseInnerAssociatedEmployeesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAdministrators200ResponseInnerAssociatedEmployeesInner(code string, key string, lastName string, firstName string) *GetAdministrators200ResponseInnerAssociatedEmployeesInner {
	this := GetAdministrators200ResponseInnerAssociatedEmployeesInner{}
	this.Code = code
	this.Key = key
	this.LastName = lastName
	this.FirstName = firstName
	return &this
}

// NewGetAdministrators200ResponseInnerAssociatedEmployeesInnerWithDefaults instantiates a new GetAdministrators200ResponseInnerAssociatedEmployeesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAdministrators200ResponseInnerAssociatedEmployeesInnerWithDefaults() *GetAdministrators200ResponseInnerAssociatedEmployeesInner {
	this := GetAdministrators200ResponseInnerAssociatedEmployeesInner{}
	return &this
}

// GetCode returns the Code field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) SetCode(v string) {
	o.Code = v
}

// GetKey returns the Key field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) SetKey(v string) {
	o.Key = v
}

// GetLastName returns the LastName field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) SetLastName(v string) {
	o.LastName = v
}

// GetFirstName returns the FirstName field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *GetAdministrators200ResponseInnerAssociatedEmployeesInner) SetFirstName(v string) {
	o.FirstName = v
}

func (o GetAdministrators200ResponseInnerAssociatedEmployeesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAdministrators200ResponseInnerAssociatedEmployeesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["key"] = o.Key
	toSerialize["lastName"] = o.LastName
	toSerialize["firstName"] = o.FirstName
	return toSerialize, nil
}

type NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner struct {
	value *GetAdministrators200ResponseInnerAssociatedEmployeesInner
	isSet bool
}

func (v NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner) Get() *GetAdministrators200ResponseInnerAssociatedEmployeesInner {
	return v.value
}

func (v *NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner) Set(val *GetAdministrators200ResponseInnerAssociatedEmployeesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAdministrators200ResponseInnerAssociatedEmployeesInner(val *GetAdministrators200ResponseInnerAssociatedEmployeesInner) *NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner {
	return &NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner{value: val, isSet: true}
}

func (v NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAdministrators200ResponseInnerAssociatedEmployeesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


