/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOvertimes200ResponseOvertimeRequestsInnerFlowInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOvertimes200ResponseOvertimeRequestsInnerFlowInner{}

// GetOvertimes200ResponseOvertimeRequestsInnerFlowInner struct for GetOvertimes200ResponseOvertimeRequestsInnerFlowInner
type GetOvertimes200ResponseOvertimeRequestsInnerFlowInner struct {
	// 承認フローレベル（１～５）
	Level int32 `json:"level"`
	// 管理者識別キー（管理者コードが変更されても不変）
	AdministratorKeys []string `json:"administratorKeys"`
}

// NewGetOvertimes200ResponseOvertimeRequestsInnerFlowInner instantiates a new GetOvertimes200ResponseOvertimeRequestsInnerFlowInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOvertimes200ResponseOvertimeRequestsInnerFlowInner(level int32, administratorKeys []string) *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner {
	this := GetOvertimes200ResponseOvertimeRequestsInnerFlowInner{}
	this.Level = level
	this.AdministratorKeys = administratorKeys
	return &this
}

// NewGetOvertimes200ResponseOvertimeRequestsInnerFlowInnerWithDefaults instantiates a new GetOvertimes200ResponseOvertimeRequestsInnerFlowInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOvertimes200ResponseOvertimeRequestsInnerFlowInnerWithDefaults() *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner {
	this := GetOvertimes200ResponseOvertimeRequestsInnerFlowInner{}
	return &this
}

// GetLevel returns the Level field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) GetLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) GetLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) SetLevel(v int32) {
	o.Level = v
}

// GetAdministratorKeys returns the AdministratorKeys field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) GetAdministratorKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AdministratorKeys
}

// GetAdministratorKeysOk returns a tuple with the AdministratorKeys field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) GetAdministratorKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdministratorKeys, true
}

// SetAdministratorKeys sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) SetAdministratorKeys(v []string) {
	o.AdministratorKeys = v
}

func (o GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	toSerialize["administratorKeys"] = o.AdministratorKeys
	return toSerialize, nil
}

type NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner struct {
	value *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner
	isSet bool
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner) Get() *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner {
	return v.value
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner) Set(val *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner(val *GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) *NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner {
	return &NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner{value: val, isSet: true}
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerFlowInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


