/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetOvertimes200ResponseOvertimeRequestsInnerCurrent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOvertimes200ResponseOvertimeRequestsInnerCurrent{}

// GetOvertimes200ResponseOvertimeRequestsInnerCurrent 現在のスケジュール
type GetOvertimes200ResponseOvertimeRequestsInnerCurrent struct {
	// 勤務予定前の時間外申請か（true 予定前　false： 予定後）
	IsBeforeSchedule bool `json:"isBeforeSchedule"`
	// 開始時刻
	Start time.Time `json:"start"`
	// 終了時刻
	End time.Time `json:"end"`
}

// NewGetOvertimes200ResponseOvertimeRequestsInnerCurrent instantiates a new GetOvertimes200ResponseOvertimeRequestsInnerCurrent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOvertimes200ResponseOvertimeRequestsInnerCurrent(isBeforeSchedule bool, start time.Time, end time.Time) *GetOvertimes200ResponseOvertimeRequestsInnerCurrent {
	this := GetOvertimes200ResponseOvertimeRequestsInnerCurrent{}
	this.IsBeforeSchedule = isBeforeSchedule
	this.Start = start
	this.End = end
	return &this
}

// NewGetOvertimes200ResponseOvertimeRequestsInnerCurrentWithDefaults instantiates a new GetOvertimes200ResponseOvertimeRequestsInnerCurrent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOvertimes200ResponseOvertimeRequestsInnerCurrentWithDefaults() *GetOvertimes200ResponseOvertimeRequestsInnerCurrent {
	this := GetOvertimes200ResponseOvertimeRequestsInnerCurrent{}
	return &this
}

// GetIsBeforeSchedule returns the IsBeforeSchedule field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) GetIsBeforeSchedule() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsBeforeSchedule
}

// GetIsBeforeScheduleOk returns a tuple with the IsBeforeSchedule field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) GetIsBeforeScheduleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBeforeSchedule, true
}

// SetIsBeforeSchedule sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) SetIsBeforeSchedule(v bool) {
	o.IsBeforeSchedule = v
}

// GetStart returns the Start field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) SetEnd(v time.Time) {
	o.End = v
}

func (o GetOvertimes200ResponseOvertimeRequestsInnerCurrent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOvertimes200ResponseOvertimeRequestsInnerCurrent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isBeforeSchedule"] = o.IsBeforeSchedule
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

type NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent struct {
	value *GetOvertimes200ResponseOvertimeRequestsInnerCurrent
	isSet bool
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent) Get() *GetOvertimes200ResponseOvertimeRequestsInnerCurrent {
	return v.value
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent) Set(val *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent(val *GetOvertimes200ResponseOvertimeRequestsInnerCurrent) *NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent {
	return &NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent{value: val, isSet: true}
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerCurrent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


