/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule{}

// GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule struct for GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule
type GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule struct {
	// 休憩開始予定
	Start time.Time `json:"start"`
	// 休憩終了予定
	End time.Time `json:"end"`
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule(start time.Time, end time.Time) *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule {
	this := GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule{}
	this.Start = start
	this.End = end
	return &this
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleWithDefaults instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakScheduleWithDefaults() *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule {
	this := GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule{}
	return &this
}

// GetStart returns the Start field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) SetEnd(v time.Time) {
	o.End = v
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

type NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule struct {
	value *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule
	isSet bool
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) Get() *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule {
	return v.value
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) Set(val *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule(val *GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule {
	return &NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule{value: val, isSet: true}
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


