/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DailyWorkingResponseCurrentDateEmployee type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyWorkingResponseCurrentDateEmployee{}

// DailyWorkingResponseCurrentDateEmployee 今日時点の従業員データ
type DailyWorkingResponseCurrentDateEmployee struct {
	// 所属コード
	DivisionCode string `json:"divisionCode"`
	// 所属名
	DivisionName string `json:"divisionName"`
	// 性別（no_selected： 選択しない　male： 男性　female： 女性）
	Gender string `json:"gender"`
	// 雇用区分コード
	TypeCode string `json:"typeCode"`
	// 雇用区分名
	TypeName string `json:"typeName"`
	// 従業員コード
	Code string `json:"code"`
	// 姓
	LastName string `json:"lastName"`
	// 名
	FirstName string `json:"firstName"`
	// 姓（カナ）
	LastNamePhonetics string `json:"lastNamePhonetics"`
	// 名（カナ）
	FirstNamePhonetics string `json:"firstNamePhonetics"`
	// 従業員グループ情報
	EmployeeGroups []EmployeeResponseEmployeeGroupsInner `json:"employeeGroups"`
}

// NewDailyWorkingResponseCurrentDateEmployee instantiates a new DailyWorkingResponseCurrentDateEmployee object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyWorkingResponseCurrentDateEmployee(divisionCode string, divisionName string, gender string, typeCode string, typeName string, code string, lastName string, firstName string, lastNamePhonetics string, firstNamePhonetics string, employeeGroups []EmployeeResponseEmployeeGroupsInner) *DailyWorkingResponseCurrentDateEmployee {
	this := DailyWorkingResponseCurrentDateEmployee{}
	this.DivisionCode = divisionCode
	this.DivisionName = divisionName
	this.Gender = gender
	this.TypeCode = typeCode
	this.TypeName = typeName
	this.Code = code
	this.LastName = lastName
	this.FirstName = firstName
	this.LastNamePhonetics = lastNamePhonetics
	this.FirstNamePhonetics = firstNamePhonetics
	this.EmployeeGroups = employeeGroups
	return &this
}

// NewDailyWorkingResponseCurrentDateEmployeeWithDefaults instantiates a new DailyWorkingResponseCurrentDateEmployee object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyWorkingResponseCurrentDateEmployeeWithDefaults() *DailyWorkingResponseCurrentDateEmployee {
	this := DailyWorkingResponseCurrentDateEmployee{}
	return &this
}

// GetDivisionCode returns the DivisionCode field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetDivisionCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DivisionCode
}

// GetDivisionCodeOk returns a tuple with the DivisionCode field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetDivisionCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DivisionCode, true
}

// SetDivisionCode sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetDivisionCode(v string) {
	o.DivisionCode = v
}

// GetDivisionName returns the DivisionName field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetDivisionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DivisionName
}

// GetDivisionNameOk returns a tuple with the DivisionName field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetDivisionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DivisionName, true
}

// SetDivisionName sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetDivisionName(v string) {
	o.DivisionName = v
}

// GetGender returns the Gender field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetGender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetGender(v string) {
	o.Gender = v
}

// GetTypeCode returns the TypeCode field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetTypeCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeCode
}

// GetTypeCodeOk returns a tuple with the TypeCode field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetTypeCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeCode, true
}

// SetTypeCode sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetTypeCode(v string) {
	o.TypeCode = v
}

// GetTypeName returns the TypeName field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeName
}

// GetTypeNameOk returns a tuple with the TypeName field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeName, true
}

// SetTypeName sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetTypeName(v string) {
	o.TypeName = v
}

// GetCode returns the Code field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetCode(v string) {
	o.Code = v
}

// GetLastName returns the LastName field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetLastName(v string) {
	o.LastName = v
}

// GetFirstName returns the FirstName field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastNamePhonetics returns the LastNamePhonetics field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetLastNamePhonetics() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastNamePhonetics
}

// GetLastNamePhoneticsOk returns a tuple with the LastNamePhonetics field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetLastNamePhoneticsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastNamePhonetics, true
}

// SetLastNamePhonetics sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetLastNamePhonetics(v string) {
	o.LastNamePhonetics = v
}

// GetFirstNamePhonetics returns the FirstNamePhonetics field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetFirstNamePhonetics() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstNamePhonetics
}

// GetFirstNamePhoneticsOk returns a tuple with the FirstNamePhonetics field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetFirstNamePhoneticsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstNamePhonetics, true
}

// SetFirstNamePhonetics sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetFirstNamePhonetics(v string) {
	o.FirstNamePhonetics = v
}

// GetEmployeeGroups returns the EmployeeGroups field value
func (o *DailyWorkingResponseCurrentDateEmployee) GetEmployeeGroups() []EmployeeResponseEmployeeGroupsInner {
	if o == nil {
		var ret []EmployeeResponseEmployeeGroupsInner
		return ret
	}

	return o.EmployeeGroups
}

// GetEmployeeGroupsOk returns a tuple with the EmployeeGroups field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCurrentDateEmployee) GetEmployeeGroupsOk() ([]EmployeeResponseEmployeeGroupsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmployeeGroups, true
}

// SetEmployeeGroups sets field value
func (o *DailyWorkingResponseCurrentDateEmployee) SetEmployeeGroups(v []EmployeeResponseEmployeeGroupsInner) {
	o.EmployeeGroups = v
}

func (o DailyWorkingResponseCurrentDateEmployee) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyWorkingResponseCurrentDateEmployee) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["divisionCode"] = o.DivisionCode
	toSerialize["divisionName"] = o.DivisionName
	toSerialize["gender"] = o.Gender
	toSerialize["typeCode"] = o.TypeCode
	toSerialize["typeName"] = o.TypeName
	toSerialize["code"] = o.Code
	toSerialize["lastName"] = o.LastName
	toSerialize["firstName"] = o.FirstName
	toSerialize["lastNamePhonetics"] = o.LastNamePhonetics
	toSerialize["firstNamePhonetics"] = o.FirstNamePhonetics
	toSerialize["employeeGroups"] = o.EmployeeGroups
	return toSerialize, nil
}

type NullableDailyWorkingResponseCurrentDateEmployee struct {
	value *DailyWorkingResponseCurrentDateEmployee
	isSet bool
}

func (v NullableDailyWorkingResponseCurrentDateEmployee) Get() *DailyWorkingResponseCurrentDateEmployee {
	return v.value
}

func (v *NullableDailyWorkingResponseCurrentDateEmployee) Set(val *DailyWorkingResponseCurrentDateEmployee) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyWorkingResponseCurrentDateEmployee) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyWorkingResponseCurrentDateEmployee) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyWorkingResponseCurrentDateEmployee(val *DailyWorkingResponseCurrentDateEmployee) *NullableDailyWorkingResponseCurrentDateEmployee {
	return &NullableDailyWorkingResponseCurrentDateEmployee{value: val, isSet: true}
}

func (v NullableDailyWorkingResponseCurrentDateEmployee) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyWorkingResponseCurrentDateEmployee) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


