/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOvertimes200ResponseOvertimeRequestsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOvertimes200ResponseOvertimeRequestsInner{}

// GetOvertimes200ResponseOvertimeRequestsInner struct for GetOvertimes200ResponseOvertimeRequestsInner
type GetOvertimes200ResponseOvertimeRequestsInner struct {
	// 対象日
	Date string `json:"date"`
	// 申請日
	RequestedDate string `json:"requestedDate"`
	// 従業員識別キー（従業員コードが変更されても不変）
	EmployeeKey string `json:"employeeKey"`
	// 申請識別キー
	RequestKey string `json:"requestKey"`
	Applicant GetOvertimes200ResponseOvertimeRequestsInnerApplicant `json:"applicant"`
	// 申請ステータス（applying 申請中　rejected： 棄却　approved： 承認）
	Status string `json:"status"`
	// 現在の承認フローレベル（１～５）
	CurrentFlow int32 `json:"currentFlow"`
	// 最終更新管理者識別キー
	LastModifiedAdministratorKey string `json:"lastModifiedAdministratorKey"`
	// 申請メッセージ
	Message string `json:"message"`
	// 管理者コメント
	AdminComment string `json:"adminComment"`
	Requested GetOvertimes200ResponseOvertimeRequestsInnerRequested `json:"requested"`
	Current GetOvertimes200ResponseOvertimeRequestsInnerCurrent `json:"current"`
	// 承認フロー
	Flow []GetOvertimes200ResponseOvertimeRequestsInnerFlowInner `json:"flow,omitempty"`
}

// NewGetOvertimes200ResponseOvertimeRequestsInner instantiates a new GetOvertimes200ResponseOvertimeRequestsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOvertimes200ResponseOvertimeRequestsInner(date string, requestedDate string, employeeKey string, requestKey string, applicant GetOvertimes200ResponseOvertimeRequestsInnerApplicant, status string, currentFlow int32, lastModifiedAdministratorKey string, message string, adminComment string, requested GetOvertimes200ResponseOvertimeRequestsInnerRequested, current GetOvertimes200ResponseOvertimeRequestsInnerCurrent) *GetOvertimes200ResponseOvertimeRequestsInner {
	this := GetOvertimes200ResponseOvertimeRequestsInner{}
	this.Date = date
	this.RequestedDate = requestedDate
	this.EmployeeKey = employeeKey
	this.RequestKey = requestKey
	this.Applicant = applicant
	this.Status = status
	this.CurrentFlow = currentFlow
	this.LastModifiedAdministratorKey = lastModifiedAdministratorKey
	this.Message = message
	this.AdminComment = adminComment
	this.Requested = requested
	this.Current = current
	return &this
}

// NewGetOvertimes200ResponseOvertimeRequestsInnerWithDefaults instantiates a new GetOvertimes200ResponseOvertimeRequestsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOvertimes200ResponseOvertimeRequestsInnerWithDefaults() *GetOvertimes200ResponseOvertimeRequestsInner {
	this := GetOvertimes200ResponseOvertimeRequestsInner{}
	return &this
}

// GetDate returns the Date field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetDate(v string) {
	o.Date = v
}

// GetRequestedDate returns the RequestedDate field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetRequestedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedDate
}

// GetRequestedDateOk returns a tuple with the RequestedDate field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetRequestedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedDate, true
}

// SetRequestedDate sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetRequestedDate(v string) {
	o.RequestedDate = v
}

// GetEmployeeKey returns the EmployeeKey field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetEmployeeKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmployeeKey
}

// GetEmployeeKeyOk returns a tuple with the EmployeeKey field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetEmployeeKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmployeeKey, true
}

// SetEmployeeKey sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetEmployeeKey(v string) {
	o.EmployeeKey = v
}

// GetRequestKey returns the RequestKey field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetRequestKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestKey
}

// GetRequestKeyOk returns a tuple with the RequestKey field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetRequestKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestKey, true
}

// SetRequestKey sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetRequestKey(v string) {
	o.RequestKey = v
}

// GetApplicant returns the Applicant field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetApplicant() GetOvertimes200ResponseOvertimeRequestsInnerApplicant {
	if o == nil {
		var ret GetOvertimes200ResponseOvertimeRequestsInnerApplicant
		return ret
	}

	return o.Applicant
}

// GetApplicantOk returns a tuple with the Applicant field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetApplicantOk() (*GetOvertimes200ResponseOvertimeRequestsInnerApplicant, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Applicant, true
}

// SetApplicant sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetApplicant(v GetOvertimes200ResponseOvertimeRequestsInnerApplicant) {
	o.Applicant = v
}

// GetStatus returns the Status field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetStatus(v string) {
	o.Status = v
}

// GetCurrentFlow returns the CurrentFlow field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetCurrentFlow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentFlow
}

// GetCurrentFlowOk returns a tuple with the CurrentFlow field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetCurrentFlowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentFlow, true
}

// SetCurrentFlow sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetCurrentFlow(v int32) {
	o.CurrentFlow = v
}

// GetLastModifiedAdministratorKey returns the LastModifiedAdministratorKey field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetLastModifiedAdministratorKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastModifiedAdministratorKey
}

// GetLastModifiedAdministratorKeyOk returns a tuple with the LastModifiedAdministratorKey field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetLastModifiedAdministratorKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModifiedAdministratorKey, true
}

// SetLastModifiedAdministratorKey sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetLastModifiedAdministratorKey(v string) {
	o.LastModifiedAdministratorKey = v
}

// GetMessage returns the Message field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetMessage(v string) {
	o.Message = v
}

// GetAdminComment returns the AdminComment field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetAdminComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdminComment
}

// GetAdminCommentOk returns a tuple with the AdminComment field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetAdminCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdminComment, true
}

// SetAdminComment sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetAdminComment(v string) {
	o.AdminComment = v
}

// GetRequested returns the Requested field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetRequested() GetOvertimes200ResponseOvertimeRequestsInnerRequested {
	if o == nil {
		var ret GetOvertimes200ResponseOvertimeRequestsInnerRequested
		return ret
	}

	return o.Requested
}

// GetRequestedOk returns a tuple with the Requested field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetRequestedOk() (*GetOvertimes200ResponseOvertimeRequestsInnerRequested, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Requested, true
}

// SetRequested sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetRequested(v GetOvertimes200ResponseOvertimeRequestsInnerRequested) {
	o.Requested = v
}

// GetCurrent returns the Current field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetCurrent() GetOvertimes200ResponseOvertimeRequestsInnerCurrent {
	if o == nil {
		var ret GetOvertimes200ResponseOvertimeRequestsInnerCurrent
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetCurrentOk() (*GetOvertimes200ResponseOvertimeRequestsInnerCurrent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetCurrent(v GetOvertimes200ResponseOvertimeRequestsInnerCurrent) {
	o.Current = v
}

// GetFlow returns the Flow field value if set, zero value otherwise.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetFlow() []GetOvertimes200ResponseOvertimeRequestsInnerFlowInner {
	if o == nil || IsNil(o.Flow) {
		var ret []GetOvertimes200ResponseOvertimeRequestsInnerFlowInner
		return ret
	}
	return o.Flow
}

// GetFlowOk returns a tuple with the Flow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) GetFlowOk() ([]GetOvertimes200ResponseOvertimeRequestsInnerFlowInner, bool) {
	if o == nil || IsNil(o.Flow) {
		return nil, false
	}
	return o.Flow, true
}

// HasFlow returns a boolean if a field has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) HasFlow() bool {
	if o != nil && !IsNil(o.Flow) {
		return true
	}

	return false
}

// SetFlow gets a reference to the given []GetOvertimes200ResponseOvertimeRequestsInnerFlowInner and assigns it to the Flow field.
func (o *GetOvertimes200ResponseOvertimeRequestsInner) SetFlow(v []GetOvertimes200ResponseOvertimeRequestsInnerFlowInner) {
	o.Flow = v
}

func (o GetOvertimes200ResponseOvertimeRequestsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOvertimes200ResponseOvertimeRequestsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["requestedDate"] = o.RequestedDate
	toSerialize["employeeKey"] = o.EmployeeKey
	toSerialize["requestKey"] = o.RequestKey
	toSerialize["applicant"] = o.Applicant
	toSerialize["status"] = o.Status
	toSerialize["currentFlow"] = o.CurrentFlow
	toSerialize["lastModifiedAdministratorKey"] = o.LastModifiedAdministratorKey
	toSerialize["message"] = o.Message
	toSerialize["adminComment"] = o.AdminComment
	toSerialize["requested"] = o.Requested
	toSerialize["current"] = o.Current
	if !IsNil(o.Flow) {
		toSerialize["flow"] = o.Flow
	}
	return toSerialize, nil
}

type NullableGetOvertimes200ResponseOvertimeRequestsInner struct {
	value *GetOvertimes200ResponseOvertimeRequestsInner
	isSet bool
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInner) Get() *GetOvertimes200ResponseOvertimeRequestsInner {
	return v.value
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInner) Set(val *GetOvertimes200ResponseOvertimeRequestsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOvertimes200ResponseOvertimeRequestsInner(val *GetOvertimes200ResponseOvertimeRequestsInner) *NullableGetOvertimes200ResponseOvertimeRequestsInner {
	return &NullableGetOvertimes200ResponseOvertimeRequestsInner{value: val, isSet: true}
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


