/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSchedules200ResponseScheduleRequestsInnerFlow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200ResponseScheduleRequestsInnerFlow{}

// GetSchedules200ResponseScheduleRequestsInnerFlow 承認フロー
type GetSchedules200ResponseScheduleRequestsInnerFlow struct {
	// 承認フローレベル（１～５）
	Level string `json:"level"`
	// 管理者識別キー（管理者コードが変更されても不変）
	AdministratorKeys string `json:"administratorKeys"`
}

// NewGetSchedules200ResponseScheduleRequestsInnerFlow instantiates a new GetSchedules200ResponseScheduleRequestsInnerFlow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200ResponseScheduleRequestsInnerFlow(level string, administratorKeys string) *GetSchedules200ResponseScheduleRequestsInnerFlow {
	this := GetSchedules200ResponseScheduleRequestsInnerFlow{}
	this.Level = level
	this.AdministratorKeys = administratorKeys
	return &this
}

// NewGetSchedules200ResponseScheduleRequestsInnerFlowWithDefaults instantiates a new GetSchedules200ResponseScheduleRequestsInnerFlow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseScheduleRequestsInnerFlowWithDefaults() *GetSchedules200ResponseScheduleRequestsInnerFlow {
	this := GetSchedules200ResponseScheduleRequestsInnerFlow{}
	return &this
}

// GetLevel returns the Level field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlow) GetLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerFlow) GetLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlow) SetLevel(v string) {
	o.Level = v
}

// GetAdministratorKeys returns the AdministratorKeys field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlow) GetAdministratorKeys() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdministratorKeys
}

// GetAdministratorKeysOk returns a tuple with the AdministratorKeys field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerFlow) GetAdministratorKeysOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdministratorKeys, true
}

// SetAdministratorKeys sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlow) SetAdministratorKeys(v string) {
	o.AdministratorKeys = v
}

func (o GetSchedules200ResponseScheduleRequestsInnerFlow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200ResponseScheduleRequestsInnerFlow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	toSerialize["administratorKeys"] = o.AdministratorKeys
	return toSerialize, nil
}

type NullableGetSchedules200ResponseScheduleRequestsInnerFlow struct {
	value *GetSchedules200ResponseScheduleRequestsInnerFlow
	isSet bool
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerFlow) Get() *GetSchedules200ResponseScheduleRequestsInnerFlow {
	return v.value
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerFlow) Set(val *GetSchedules200ResponseScheduleRequestsInnerFlow) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerFlow) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerFlow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200ResponseScheduleRequestsInnerFlow(val *GetSchedules200ResponseScheduleRequestsInnerFlow) *NullableGetSchedules200ResponseScheduleRequestsInnerFlow {
	return &NullableGetSchedules200ResponseScheduleRequestsInnerFlow{value: val, isSet: true}
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerFlow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerFlow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


