/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetSchedules200ResponseScheduleRequestsInnerRequested type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200ResponseScheduleRequestsInnerRequested{}

// GetSchedules200ResponseScheduleRequestsInnerRequested struct for GetSchedules200ResponseScheduleRequestsInnerRequested
type GetSchedules200ResponseScheduleRequestsInnerRequested struct {
	// 出勤予定時間
	ClockInSchedule time.Time `json:"clockInSchedule"`
	// 退勤予定時間
	ClockOutSchedule time.Time `json:"clockOutSchedule"`
	// 休憩予定時間（分）
	BreakSchedule int32 `json:"breakSchedule"`
	StartEndBreakSchedule GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule `json:"startEndBreakSchedule"`
	HolidaysObtained GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtained `json:"holidaysObtained"`
	// 勤務日種別名
	WorkDayTypeName string `json:"workDayTypeName"`
	// 残業上限時間（分）
	OvertimeUpperLimit *int32 `json:"overtimeUpperLimit,omitempty"`
	// 出勤先所属コード
	WorkPlaceDivisionCode string `json:"workPlaceDivisionCode"`
	// 出勤先所属名
	WorkPlaceDivisionName string `json:"workPlaceDivisionName"`
	// 振替出勤
	SubstitutionClockInName string `json:"substitutionClockInName"`
	// スケジュール種別
	ScheduleTypeName string `json:"scheduleTypeName"`
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequested instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequested object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200ResponseScheduleRequestsInnerRequested(clockInSchedule time.Time, clockOutSchedule time.Time, breakSchedule int32, startEndBreakSchedule GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule, holidaysObtained GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtained, workDayTypeName string, workPlaceDivisionCode string, workPlaceDivisionName string, substitutionClockInName string, scheduleTypeName string) *GetSchedules200ResponseScheduleRequestsInnerRequested {
	this := GetSchedules200ResponseScheduleRequestsInnerRequested{}
	this.ClockInSchedule = clockInSchedule
	this.ClockOutSchedule = clockOutSchedule
	this.BreakSchedule = breakSchedule
	this.StartEndBreakSchedule = startEndBreakSchedule
	this.HolidaysObtained = holidaysObtained
	this.WorkDayTypeName = workDayTypeName
	this.WorkPlaceDivisionCode = workPlaceDivisionCode
	this.WorkPlaceDivisionName = workPlaceDivisionName
	this.SubstitutionClockInName = substitutionClockInName
	this.ScheduleTypeName = scheduleTypeName
	return &this
}

// NewGetSchedules200ResponseScheduleRequestsInnerRequestedWithDefaults instantiates a new GetSchedules200ResponseScheduleRequestsInnerRequested object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseScheduleRequestsInnerRequestedWithDefaults() *GetSchedules200ResponseScheduleRequestsInnerRequested {
	this := GetSchedules200ResponseScheduleRequestsInnerRequested{}
	return &this
}

// GetClockInSchedule returns the ClockInSchedule field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetClockInSchedule() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ClockInSchedule
}

// GetClockInScheduleOk returns a tuple with the ClockInSchedule field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetClockInScheduleOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClockInSchedule, true
}

// SetClockInSchedule sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetClockInSchedule(v time.Time) {
	o.ClockInSchedule = v
}

// GetClockOutSchedule returns the ClockOutSchedule field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetClockOutSchedule() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ClockOutSchedule
}

// GetClockOutScheduleOk returns a tuple with the ClockOutSchedule field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetClockOutScheduleOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClockOutSchedule, true
}

// SetClockOutSchedule sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetClockOutSchedule(v time.Time) {
	o.ClockOutSchedule = v
}

// GetBreakSchedule returns the BreakSchedule field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetBreakSchedule() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BreakSchedule
}

// GetBreakScheduleOk returns a tuple with the BreakSchedule field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetBreakScheduleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BreakSchedule, true
}

// SetBreakSchedule sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetBreakSchedule(v int32) {
	o.BreakSchedule = v
}

// GetStartEndBreakSchedule returns the StartEndBreakSchedule field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetStartEndBreakSchedule() GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule {
	if o == nil {
		var ret GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule
		return ret
	}

	return o.StartEndBreakSchedule
}

// GetStartEndBreakScheduleOk returns a tuple with the StartEndBreakSchedule field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetStartEndBreakScheduleOk() (*GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartEndBreakSchedule, true
}

// SetStartEndBreakSchedule sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetStartEndBreakSchedule(v GetSchedules200ResponseScheduleRequestsInnerRequestedStartEndBreakSchedule) {
	o.StartEndBreakSchedule = v
}

// GetHolidaysObtained returns the HolidaysObtained field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetHolidaysObtained() GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtained {
	if o == nil {
		var ret GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtained
		return ret
	}

	return o.HolidaysObtained
}

// GetHolidaysObtainedOk returns a tuple with the HolidaysObtained field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetHolidaysObtainedOk() (*GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtained, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HolidaysObtained, true
}

// SetHolidaysObtained sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetHolidaysObtained(v GetSchedules200ResponseScheduleRequestsInnerRequestedHolidaysObtained) {
	o.HolidaysObtained = v
}

// GetWorkDayTypeName returns the WorkDayTypeName field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetWorkDayTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkDayTypeName
}

// GetWorkDayTypeNameOk returns a tuple with the WorkDayTypeName field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetWorkDayTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkDayTypeName, true
}

// SetWorkDayTypeName sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetWorkDayTypeName(v string) {
	o.WorkDayTypeName = v
}

// GetOvertimeUpperLimit returns the OvertimeUpperLimit field value if set, zero value otherwise.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetOvertimeUpperLimit() int32 {
	if o == nil || IsNil(o.OvertimeUpperLimit) {
		var ret int32
		return ret
	}
	return *o.OvertimeUpperLimit
}

// GetOvertimeUpperLimitOk returns a tuple with the OvertimeUpperLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetOvertimeUpperLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.OvertimeUpperLimit) {
		return nil, false
	}
	return o.OvertimeUpperLimit, true
}

// HasOvertimeUpperLimit returns a boolean if a field has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) HasOvertimeUpperLimit() bool {
	if o != nil && !IsNil(o.OvertimeUpperLimit) {
		return true
	}

	return false
}

// SetOvertimeUpperLimit gets a reference to the given int32 and assigns it to the OvertimeUpperLimit field.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetOvertimeUpperLimit(v int32) {
	o.OvertimeUpperLimit = &v
}

// GetWorkPlaceDivisionCode returns the WorkPlaceDivisionCode field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetWorkPlaceDivisionCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkPlaceDivisionCode
}

// GetWorkPlaceDivisionCodeOk returns a tuple with the WorkPlaceDivisionCode field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetWorkPlaceDivisionCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkPlaceDivisionCode, true
}

// SetWorkPlaceDivisionCode sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetWorkPlaceDivisionCode(v string) {
	o.WorkPlaceDivisionCode = v
}

// GetWorkPlaceDivisionName returns the WorkPlaceDivisionName field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetWorkPlaceDivisionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkPlaceDivisionName
}

// GetWorkPlaceDivisionNameOk returns a tuple with the WorkPlaceDivisionName field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetWorkPlaceDivisionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkPlaceDivisionName, true
}

// SetWorkPlaceDivisionName sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetWorkPlaceDivisionName(v string) {
	o.WorkPlaceDivisionName = v
}

// GetSubstitutionClockInName returns the SubstitutionClockInName field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetSubstitutionClockInName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubstitutionClockInName
}

// GetSubstitutionClockInNameOk returns a tuple with the SubstitutionClockInName field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetSubstitutionClockInNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubstitutionClockInName, true
}

// SetSubstitutionClockInName sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetSubstitutionClockInName(v string) {
	o.SubstitutionClockInName = v
}

// GetScheduleTypeName returns the ScheduleTypeName field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetScheduleTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScheduleTypeName
}

// GetScheduleTypeNameOk returns a tuple with the ScheduleTypeName field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) GetScheduleTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduleTypeName, true
}

// SetScheduleTypeName sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerRequested) SetScheduleTypeName(v string) {
	o.ScheduleTypeName = v
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequested) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200ResponseScheduleRequestsInnerRequested) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clockInSchedule"] = o.ClockInSchedule
	toSerialize["clockOutSchedule"] = o.ClockOutSchedule
	toSerialize["breakSchedule"] = o.BreakSchedule
	toSerialize["startEndBreakSchedule"] = o.StartEndBreakSchedule
	toSerialize["holidaysObtained"] = o.HolidaysObtained
	toSerialize["workDayTypeName"] = o.WorkDayTypeName
	if !IsNil(o.OvertimeUpperLimit) {
		toSerialize["overtimeUpperLimit"] = o.OvertimeUpperLimit
	}
	toSerialize["workPlaceDivisionCode"] = o.WorkPlaceDivisionCode
	toSerialize["workPlaceDivisionName"] = o.WorkPlaceDivisionName
	toSerialize["substitutionClockInName"] = o.SubstitutionClockInName
	toSerialize["scheduleTypeName"] = o.ScheduleTypeName
	return toSerialize, nil
}

type NullableGetSchedules200ResponseScheduleRequestsInnerRequested struct {
	value *GetSchedules200ResponseScheduleRequestsInnerRequested
	isSet bool
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequested) Get() *GetSchedules200ResponseScheduleRequestsInnerRequested {
	return v.value
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequested) Set(val *GetSchedules200ResponseScheduleRequestsInnerRequested) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequested) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequested) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200ResponseScheduleRequestsInnerRequested(val *GetSchedules200ResponseScheduleRequestsInnerRequested) *NullableGetSchedules200ResponseScheduleRequestsInnerRequested {
	return &NullableGetSchedules200ResponseScheduleRequestsInnerRequested{value: val, isSet: true}
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerRequested) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerRequested) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


