/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DailyWorkingResponseCustomDailyWorkings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyWorkingResponseCustomDailyWorkings{}

// DailyWorkingResponseCustomDailyWorkings struct for DailyWorkingResponseCustomDailyWorkings
type DailyWorkingResponseCustomDailyWorkings struct {
	// 日別カスタム表示コード
	Code string `json:"code"`
	// 日別カスタム表示名
	Name string `json:"name"`
	// 計算単位コード（1： 日数　2： 時間　4： 数値）
	CalculationUnitCode int32 `json:"calculationUnitCode"`
	// 計算結果
	CalculationResult int32 `json:"calculationResult"`
}

// NewDailyWorkingResponseCustomDailyWorkings instantiates a new DailyWorkingResponseCustomDailyWorkings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyWorkingResponseCustomDailyWorkings(code string, name string, calculationUnitCode int32, calculationResult int32) *DailyWorkingResponseCustomDailyWorkings {
	this := DailyWorkingResponseCustomDailyWorkings{}
	this.Code = code
	this.Name = name
	this.CalculationUnitCode = calculationUnitCode
	this.CalculationResult = calculationResult
	return &this
}

// NewDailyWorkingResponseCustomDailyWorkingsWithDefaults instantiates a new DailyWorkingResponseCustomDailyWorkings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyWorkingResponseCustomDailyWorkingsWithDefaults() *DailyWorkingResponseCustomDailyWorkings {
	this := DailyWorkingResponseCustomDailyWorkings{}
	return &this
}

// GetCode returns the Code field value
func (o *DailyWorkingResponseCustomDailyWorkings) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCustomDailyWorkings) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DailyWorkingResponseCustomDailyWorkings) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *DailyWorkingResponseCustomDailyWorkings) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCustomDailyWorkings) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DailyWorkingResponseCustomDailyWorkings) SetName(v string) {
	o.Name = v
}

// GetCalculationUnitCode returns the CalculationUnitCode field value
func (o *DailyWorkingResponseCustomDailyWorkings) GetCalculationUnitCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CalculationUnitCode
}

// GetCalculationUnitCodeOk returns a tuple with the CalculationUnitCode field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCustomDailyWorkings) GetCalculationUnitCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CalculationUnitCode, true
}

// SetCalculationUnitCode sets field value
func (o *DailyWorkingResponseCustomDailyWorkings) SetCalculationUnitCode(v int32) {
	o.CalculationUnitCode = v
}

// GetCalculationResult returns the CalculationResult field value
func (o *DailyWorkingResponseCustomDailyWorkings) GetCalculationResult() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CalculationResult
}

// GetCalculationResultOk returns a tuple with the CalculationResult field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseCustomDailyWorkings) GetCalculationResultOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CalculationResult, true
}

// SetCalculationResult sets field value
func (o *DailyWorkingResponseCustomDailyWorkings) SetCalculationResult(v int32) {
	o.CalculationResult = v
}

func (o DailyWorkingResponseCustomDailyWorkings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyWorkingResponseCustomDailyWorkings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	toSerialize["calculationUnitCode"] = o.CalculationUnitCode
	toSerialize["calculationResult"] = o.CalculationResult
	return toSerialize, nil
}

type NullableDailyWorkingResponseCustomDailyWorkings struct {
	value *DailyWorkingResponseCustomDailyWorkings
	isSet bool
}

func (v NullableDailyWorkingResponseCustomDailyWorkings) Get() *DailyWorkingResponseCustomDailyWorkings {
	return v.value
}

func (v *NullableDailyWorkingResponseCustomDailyWorkings) Set(val *DailyWorkingResponseCustomDailyWorkings) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyWorkingResponseCustomDailyWorkings) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyWorkingResponseCustomDailyWorkings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyWorkingResponseCustomDailyWorkings(val *DailyWorkingResponseCustomDailyWorkings) *NullableDailyWorkingResponseCustomDailyWorkings {
	return &NullableDailyWorkingResponseCustomDailyWorkings{value: val, isSet: true}
}

func (v NullableDailyWorkingResponseCustomDailyWorkings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyWorkingResponseCustomDailyWorkings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


