/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSchedules200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200Response{}

// GetSchedules200Response struct for GetSchedules200Response
type GetSchedules200Response struct {
	Year int32 `json:"year"`
	Month int32 `json:"month"`
	ScheduleRequests []GetSchedules200ResponseScheduleRequestsInner `json:"scheduleRequests"`
}

// NewGetSchedules200Response instantiates a new GetSchedules200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200Response(year int32, month int32, scheduleRequests []GetSchedules200ResponseScheduleRequestsInner) *GetSchedules200Response {
	this := GetSchedules200Response{}
	this.Year = year
	this.Month = month
	this.ScheduleRequests = scheduleRequests
	return &this
}

// NewGetSchedules200ResponseWithDefaults instantiates a new GetSchedules200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseWithDefaults() *GetSchedules200Response {
	this := GetSchedules200Response{}
	return &this
}

// GetYear returns the Year field value
func (o *GetSchedules200Response) GetYear() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Year
}

// GetYearOk returns a tuple with the Year field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200Response) GetYearOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Year, true
}

// SetYear sets field value
func (o *GetSchedules200Response) SetYear(v int32) {
	o.Year = v
}

// GetMonth returns the Month field value
func (o *GetSchedules200Response) GetMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Month
}

// GetMonthOk returns a tuple with the Month field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200Response) GetMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Month, true
}

// SetMonth sets field value
func (o *GetSchedules200Response) SetMonth(v int32) {
	o.Month = v
}

// GetScheduleRequests returns the ScheduleRequests field value
func (o *GetSchedules200Response) GetScheduleRequests() []GetSchedules200ResponseScheduleRequestsInner {
	if o == nil {
		var ret []GetSchedules200ResponseScheduleRequestsInner
		return ret
	}

	return o.ScheduleRequests
}

// GetScheduleRequestsOk returns a tuple with the ScheduleRequests field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200Response) GetScheduleRequestsOk() ([]GetSchedules200ResponseScheduleRequestsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScheduleRequests, true
}

// SetScheduleRequests sets field value
func (o *GetSchedules200Response) SetScheduleRequests(v []GetSchedules200ResponseScheduleRequestsInner) {
	o.ScheduleRequests = v
}

func (o GetSchedules200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["year"] = o.Year
	toSerialize["month"] = o.Month
	toSerialize["scheduleRequests"] = o.ScheduleRequests
	return toSerialize, nil
}

type NullableGetSchedules200Response struct {
	value *GetSchedules200Response
	isSet bool
}

func (v NullableGetSchedules200Response) Get() *GetSchedules200Response {
	return v.value
}

func (v *NullableGetSchedules200Response) Set(val *GetSchedules200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200Response(val *GetSchedules200Response) *NullableGetSchedules200Response {
	return &NullableGetSchedules200Response{value: val, isSet: true}
}

func (v NullableGetSchedules200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


