/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOvertimes200ResponseOvertimeRequestsInnerApplicant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOvertimes200ResponseOvertimeRequestsInnerApplicant{}

// GetOvertimes200ResponseOvertimeRequestsInnerApplicant 申請者
type GetOvertimes200ResponseOvertimeRequestsInnerApplicant struct {
	// 種別（employee： 従業員　administrator： 管理者)
	Type string `json:"type"`
	// 識別キー（従業員 または 管理者）
	Key string `json:"key"`
}

// NewGetOvertimes200ResponseOvertimeRequestsInnerApplicant instantiates a new GetOvertimes200ResponseOvertimeRequestsInnerApplicant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOvertimes200ResponseOvertimeRequestsInnerApplicant(type_ string, key string) *GetOvertimes200ResponseOvertimeRequestsInnerApplicant {
	this := GetOvertimes200ResponseOvertimeRequestsInnerApplicant{}
	this.Type = type_
	this.Key = key
	return &this
}

// NewGetOvertimes200ResponseOvertimeRequestsInnerApplicantWithDefaults instantiates a new GetOvertimes200ResponseOvertimeRequestsInnerApplicant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOvertimes200ResponseOvertimeRequestsInnerApplicantWithDefaults() *GetOvertimes200ResponseOvertimeRequestsInnerApplicant {
	this := GetOvertimes200ResponseOvertimeRequestsInnerApplicant{}
	return &this
}

// GetType returns the Type field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) SetType(v string) {
	o.Type = v
}

// GetKey returns the Key field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) SetKey(v string) {
	o.Key = v
}

func (o GetOvertimes200ResponseOvertimeRequestsInnerApplicant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOvertimes200ResponseOvertimeRequestsInnerApplicant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

type NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant struct {
	value *GetOvertimes200ResponseOvertimeRequestsInnerApplicant
	isSet bool
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant) Get() *GetOvertimes200ResponseOvertimeRequestsInnerApplicant {
	return v.value
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant) Set(val *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant(val *GetOvertimes200ResponseOvertimeRequestsInnerApplicant) *NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant {
	return &NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant{value: val, isSet: true}
}

func (v NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOvertimes200ResponseOvertimeRequestsInnerApplicant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


