/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DailyWorkingResponseHolidaysObtained type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyWorkingResponseHolidaysObtained{}

// DailyWorkingResponseHolidaysObtained 休暇取得
type DailyWorkingResponseHolidaysObtained struct {
	FulltimeHoliday DailyWorkingResponseHolidaysObtainedFulltimeHoliday `json:"fulltimeHoliday"`
	HalfdayHolidays DailyWorkingResponseHolidaysObtainedHalfdayHolidays `json:"halfdayHolidays"`
	HourHolidays DailyWorkingResponseHolidaysObtainedHourHolidays `json:"hourHolidays"`
}

// NewDailyWorkingResponseHolidaysObtained instantiates a new DailyWorkingResponseHolidaysObtained object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyWorkingResponseHolidaysObtained(fulltimeHoliday DailyWorkingResponseHolidaysObtainedFulltimeHoliday, halfdayHolidays DailyWorkingResponseHolidaysObtainedHalfdayHolidays, hourHolidays DailyWorkingResponseHolidaysObtainedHourHolidays) *DailyWorkingResponseHolidaysObtained {
	this := DailyWorkingResponseHolidaysObtained{}
	this.FulltimeHoliday = fulltimeHoliday
	this.HalfdayHolidays = halfdayHolidays
	this.HourHolidays = hourHolidays
	return &this
}

// NewDailyWorkingResponseHolidaysObtainedWithDefaults instantiates a new DailyWorkingResponseHolidaysObtained object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyWorkingResponseHolidaysObtainedWithDefaults() *DailyWorkingResponseHolidaysObtained {
	this := DailyWorkingResponseHolidaysObtained{}
	return &this
}

// GetFulltimeHoliday returns the FulltimeHoliday field value
func (o *DailyWorkingResponseHolidaysObtained) GetFulltimeHoliday() DailyWorkingResponseHolidaysObtainedFulltimeHoliday {
	if o == nil {
		var ret DailyWorkingResponseHolidaysObtainedFulltimeHoliday
		return ret
	}

	return o.FulltimeHoliday
}

// GetFulltimeHolidayOk returns a tuple with the FulltimeHoliday field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseHolidaysObtained) GetFulltimeHolidayOk() (*DailyWorkingResponseHolidaysObtainedFulltimeHoliday, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FulltimeHoliday, true
}

// SetFulltimeHoliday sets field value
func (o *DailyWorkingResponseHolidaysObtained) SetFulltimeHoliday(v DailyWorkingResponseHolidaysObtainedFulltimeHoliday) {
	o.FulltimeHoliday = v
}

// GetHalfdayHolidays returns the HalfdayHolidays field value
func (o *DailyWorkingResponseHolidaysObtained) GetHalfdayHolidays() DailyWorkingResponseHolidaysObtainedHalfdayHolidays {
	if o == nil {
		var ret DailyWorkingResponseHolidaysObtainedHalfdayHolidays
		return ret
	}

	return o.HalfdayHolidays
}

// GetHalfdayHolidaysOk returns a tuple with the HalfdayHolidays field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseHolidaysObtained) GetHalfdayHolidaysOk() (*DailyWorkingResponseHolidaysObtainedHalfdayHolidays, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HalfdayHolidays, true
}

// SetHalfdayHolidays sets field value
func (o *DailyWorkingResponseHolidaysObtained) SetHalfdayHolidays(v DailyWorkingResponseHolidaysObtainedHalfdayHolidays) {
	o.HalfdayHolidays = v
}

// GetHourHolidays returns the HourHolidays field value
func (o *DailyWorkingResponseHolidaysObtained) GetHourHolidays() DailyWorkingResponseHolidaysObtainedHourHolidays {
	if o == nil {
		var ret DailyWorkingResponseHolidaysObtainedHourHolidays
		return ret
	}

	return o.HourHolidays
}

// GetHourHolidaysOk returns a tuple with the HourHolidays field value
// and a boolean to check if the value has been set.
func (o *DailyWorkingResponseHolidaysObtained) GetHourHolidaysOk() (*DailyWorkingResponseHolidaysObtainedHourHolidays, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HourHolidays, true
}

// SetHourHolidays sets field value
func (o *DailyWorkingResponseHolidaysObtained) SetHourHolidays(v DailyWorkingResponseHolidaysObtainedHourHolidays) {
	o.HourHolidays = v
}

func (o DailyWorkingResponseHolidaysObtained) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyWorkingResponseHolidaysObtained) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fulltimeHoliday"] = o.FulltimeHoliday
	toSerialize["halfdayHolidays"] = o.HalfdayHolidays
	toSerialize["hourHolidays"] = o.HourHolidays
	return toSerialize, nil
}

type NullableDailyWorkingResponseHolidaysObtained struct {
	value *DailyWorkingResponseHolidaysObtained
	isSet bool
}

func (v NullableDailyWorkingResponseHolidaysObtained) Get() *DailyWorkingResponseHolidaysObtained {
	return v.value
}

func (v *NullableDailyWorkingResponseHolidaysObtained) Set(val *DailyWorkingResponseHolidaysObtained) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyWorkingResponseHolidaysObtained) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyWorkingResponseHolidaysObtained) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyWorkingResponseHolidaysObtained(val *DailyWorkingResponseHolidaysObtained) *NullableDailyWorkingResponseHolidaysObtained {
	return &NullableDailyWorkingResponseHolidaysObtained{value: val, isSet: true}
}

func (v NullableDailyWorkingResponseHolidaysObtained) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyWorkingResponseHolidaysObtained) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


