/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEmployeeGroups200ResponseInnerCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmployeeGroups200ResponseInnerCategory{}

// GetEmployeeGroups200ResponseInnerCategory 従業員グループカテゴリ
type GetEmployeeGroups200ResponseInnerCategory struct {
	// 従業員グループカテゴリコード
	Code string `json:"code"`
	// 従業員グループカテゴリ名
	Name string `json:"name"`
}

// NewGetEmployeeGroups200ResponseInnerCategory instantiates a new GetEmployeeGroups200ResponseInnerCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmployeeGroups200ResponseInnerCategory(code string, name string) *GetEmployeeGroups200ResponseInnerCategory {
	this := GetEmployeeGroups200ResponseInnerCategory{}
	this.Code = code
	this.Name = name
	return &this
}

// NewGetEmployeeGroups200ResponseInnerCategoryWithDefaults instantiates a new GetEmployeeGroups200ResponseInnerCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmployeeGroups200ResponseInnerCategoryWithDefaults() *GetEmployeeGroups200ResponseInnerCategory {
	this := GetEmployeeGroups200ResponseInnerCategory{}
	return &this
}

// GetCode returns the Code field value
func (o *GetEmployeeGroups200ResponseInnerCategory) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetEmployeeGroups200ResponseInnerCategory) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetEmployeeGroups200ResponseInnerCategory) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *GetEmployeeGroups200ResponseInnerCategory) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetEmployeeGroups200ResponseInnerCategory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetEmployeeGroups200ResponseInnerCategory) SetName(v string) {
	o.Name = v
}

func (o GetEmployeeGroups200ResponseInnerCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmployeeGroups200ResponseInnerCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableGetEmployeeGroups200ResponseInnerCategory struct {
	value *GetEmployeeGroups200ResponseInnerCategory
	isSet bool
}

func (v NullableGetEmployeeGroups200ResponseInnerCategory) Get() *GetEmployeeGroups200ResponseInnerCategory {
	return v.value
}

func (v *NullableGetEmployeeGroups200ResponseInnerCategory) Set(val *GetEmployeeGroups200ResponseInnerCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmployeeGroups200ResponseInnerCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmployeeGroups200ResponseInnerCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmployeeGroups200ResponseInnerCategory(val *GetEmployeeGroups200ResponseInnerCategory) *NullableGetEmployeeGroups200ResponseInnerCategory {
	return &NullableGetEmployeeGroups200ResponseInnerCategory{value: val, isSet: true}
}

func (v NullableGetEmployeeGroups200ResponseInnerCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmployeeGroups200ResponseInnerCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


