/*
KING OF TIME WebAPI

KING OF TIME WebAPI specification https://developer.kingtime.jp/

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSchedules200ResponseScheduleRequestsInnerFlowInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSchedules200ResponseScheduleRequestsInnerFlowInner{}

// GetSchedules200ResponseScheduleRequestsInnerFlowInner struct for GetSchedules200ResponseScheduleRequestsInnerFlowInner
type GetSchedules200ResponseScheduleRequestsInnerFlowInner struct {
	// 承認フローレベル（１～５）
	Level int32 `json:"level"`
	// 管理者識別キー（管理者コードが変更されても不変）
	AdministratorKeys []string `json:"administratorKeys"`
}

// NewGetSchedules200ResponseScheduleRequestsInnerFlowInner instantiates a new GetSchedules200ResponseScheduleRequestsInnerFlowInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSchedules200ResponseScheduleRequestsInnerFlowInner(level int32, administratorKeys []string) *GetSchedules200ResponseScheduleRequestsInnerFlowInner {
	this := GetSchedules200ResponseScheduleRequestsInnerFlowInner{}
	this.Level = level
	this.AdministratorKeys = administratorKeys
	return &this
}

// NewGetSchedules200ResponseScheduleRequestsInnerFlowInnerWithDefaults instantiates a new GetSchedules200ResponseScheduleRequestsInnerFlowInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSchedules200ResponseScheduleRequestsInnerFlowInnerWithDefaults() *GetSchedules200ResponseScheduleRequestsInnerFlowInner {
	this := GetSchedules200ResponseScheduleRequestsInnerFlowInner{}
	return &this
}

// GetLevel returns the Level field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlowInner) GetLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerFlowInner) GetLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlowInner) SetLevel(v int32) {
	o.Level = v
}

// GetAdministratorKeys returns the AdministratorKeys field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlowInner) GetAdministratorKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AdministratorKeys
}

// GetAdministratorKeysOk returns a tuple with the AdministratorKeys field value
// and a boolean to check if the value has been set.
func (o *GetSchedules200ResponseScheduleRequestsInnerFlowInner) GetAdministratorKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdministratorKeys, true
}

// SetAdministratorKeys sets field value
func (o *GetSchedules200ResponseScheduleRequestsInnerFlowInner) SetAdministratorKeys(v []string) {
	o.AdministratorKeys = v
}

func (o GetSchedules200ResponseScheduleRequestsInnerFlowInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSchedules200ResponseScheduleRequestsInnerFlowInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	toSerialize["administratorKeys"] = o.AdministratorKeys
	return toSerialize, nil
}

type NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner struct {
	value *GetSchedules200ResponseScheduleRequestsInnerFlowInner
	isSet bool
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner) Get() *GetSchedules200ResponseScheduleRequestsInnerFlowInner {
	return v.value
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner) Set(val *GetSchedules200ResponseScheduleRequestsInnerFlowInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSchedules200ResponseScheduleRequestsInnerFlowInner(val *GetSchedules200ResponseScheduleRequestsInnerFlowInner) *NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner {
	return &NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner{value: val, isSet: true}
}

func (v NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSchedules200ResponseScheduleRequestsInnerFlowInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


