type: object
description: 企業設定情報
required:
  - timeDisplayFormat
  - decimalTreatType
properties:
  timeDisplayFormat:
    type: string
    enum:
      - decimal
      - sexagesimal
    description: 表示形式（decimal： 10進法　sexagesimal： 60進法）
  decimalTreatType:
    type: string
    enum:
      - roundDown
      - roundUp
      - round
    description: 10進表示の小数第3位の扱い（roundDown： 切下げ　roundUp： 切上げ　round： 四捨五入）