openapi: 3.0.3

info:
  version: 1.0.0
  title: KING OF TIME WebAPI
  description: >-
    KING OF TIME WebAPI specification
    https://developer.kingtime.jp/

servers:
  - url: https://api.kingtime.jp/v1.0
    description: Production server (uses live data)

paths:
  $ref: "./paths/index.yml"

components:
  $ref: "./components/index.yml"
