openapi: 3.0.3

info:
  version: 1.0.0
  title: KING OF TIME WebAPI
  description: >-
    KING OF TIME WebAPI specification
    https://developer.kingtime.jp/

servers:
  - url: https://api.kingtime.jp/v1.0
    description: Production server (uses live data)
  - url: http://localhost:8001
    description: Local server (uses mock data)

paths:
  $ref: "./paths/index.yml"

components:
  $ref: "./components/index.yml"

security:
  - Bearer: []

tags:
  - name: Token
    externalDocs:
      url: https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3
  - name: Company
    externalDocs:
      url: https://developer.kingtime.jp/#%E4%BC%81%E6%A5%AD%E6%83%85%E5%A0%B1
  - name: Administrator
    externalDocs:
      url: https://developer.kingtime.jp/#%E7%AE%A1%E7%90%86%E8%80%85
  - name: Employee
    externalDocs:
      url: https://developer.kingtime.jp/#%E5%BE%93%E6%A5%AD%E5%93%A1
  - name: Attendance
    externalDocs:
      url: https://developer.kingtime.jp/#%E5%8B%A4%E6%80%A0
  - name: Request
    externalDocs:
      url: https://developer.kingtime.jp/#%E7%94%B3%E8%AB%8B
