openapi: 3.0.3
info:
  version: 1.0.0
  title: KING OF TIME WebAPI
  description: 'KING OF TIME WebAPI specification https://developer.kingtime.jp/'
servers:
  - url: 'https://api.kingtime.jp/v1.0'
    description: Production server (uses live data)
paths:
  /.healthcheck:
    get:
      operationId: GetHealthCheck
      description: ヘルスチェックを行う
      responses:
        '200':
          description: Returns a list of data sets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthcheck'
components:
  schemas:
    healthcheck:
      type: object
      required:
        - result
      properties:
        result:
          type: string
          description: success or failure
          example: success
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
tags:
  - name: トークン
    url: 'https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3'
