openapi: 3.0.3
info:
  version: 1.0.0
  title: KING OF TIME WebAPI
  description: 'KING OF TIME WebAPI specification https://developer.kingtime.jp/'
servers:
  - url: 'https://api.kingtime.jp/v1.0'
    description: Production server (uses live data)
paths:
  '/tokens/{token}':
    post:
      operationId: RefreshAccessToken
      parameters:
        - $ref: '#/components/parameters/token'
      tags:
        - Token
      description: 指定されたアクセストークンを利用停止し、新たに同じ設定でアクセストークンを発行する。
      externalDocs:
        url: 'https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-post'
      responses:
        '201':
          description: ''
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    description: refreshed access token
                    example: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    delete:
      operationId: SuspendAccessToken
      parameters:
        - $ref: '#/components/parameters/token'
      tags:
        - Token
      description: 指定されたアクセストークンを利用停止する。
      externalDocs:
        url: 'https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-delete'
      responses:
        '204':
          description: This response has no content.
  '/tokens/{token}/available':
    get:
      operationId: GetAccessTokenAvailability
      parameters:
        - $ref: '#/components/parameters/token'
      tags:
        - Token
      description: 指定されたアクセストークンが有効か確認する。
      externalDocs:
        url: 'https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-get'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                required:
                  - available
                properties:
                  available:
                    type: boolean
  /company:
    get:
      operationId: GetCompany
      tags:
        - Company
      description: 企業情報データを取得する。
      externalDocs:
        url: 'https://developer.kingtime.jp/#%E4%BC%81%E6%A5%AD%E6%83%85%E5%A0%B1-%E4%BC%81%E6%A5%AD%E6%83%85%E5%A0%B1%E3%83%87%E3%83%BC%E3%82%BF-get'
      responses:
        '200':
          description: ''
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                required:
                  - key
                  - code
                  - name
                  - host
                  - businessYearStartDate
                  - settings
                properties:
                  key:
                    type: string
                  code:
                    type: string
                  name:
                    type: string
                  host:
                    type: string
                  businessYearStartDate:
                    type: string
                  settings:
                    type: object
                    required:
                      - timeDisplayFormat
                      - decimalTreatType
                    properties:
                      timeDisplayFormat:
                        type: string
                      decimalTreatType:
                        type: string
                example:
                  key: 1qazxsw23edc....
                  code: cmp
                  name: 企業名
                  host: s2.kingtime.jp
                  businessYearStartDate: 04/01
                  settings:
                    timeDisplayFormat: decimal
                    decimalTreatType: roundUp
components:
  parameters:
    token:
      name: token
      in: path
      description: 処理対象のトークン
      required: true
      schema:
        type: string
        example: 8j9f7v4893y58rvt7nyfq2893n75tr78937n83
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
security:
  - Bearer: []
tags:
  - name: Token
    externalDocs:
      url: 'https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3'
  - name: Company
    externalDocs:
      url: 'https://developer.kingtime.jp/#%E4%BC%81%E6%A5%AD%E6%83%85%E5%A0%B1'
