name: Client Test Go

on:
  push:
    paths:
      - client/go/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start mock server
        run: docker compose up swagger-mock-api -d
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Test
        working-directory: client/go
        run: go test ./...
